### ISSUE TITLE
Build failure on Ubuntu 16.04, due to bash completion changes

### ISSUE THREAD

**Issue by ralight** [jpmens/jo#105]
```
./configure: line 4512: syntax error near unexpected token `bashcompdir,' ./configure: line 4512: `PKG_CHECK_VAR(bashcompdir, bash-completion, completionsdir, ,'
```

From https://launchpadlibrarian.net/449739274/buildlog_snap_ubuntu_xenial_arm64_jo_BUILDING.txt.gz

That's all the checking I've done so far.

**Comment by jpmens** [comment]
Yes, @scop is helping us on this in https://github.com/jpmens/jo/pull/102

**Comment by jpmens** [comment]
Travis CI build now passes on Linux and OSX

**Comment by scop** [comment]
If the launchpadlibrarian.net build is from git and does autoreconf, you'll most likely require at least pkg-config installed in order to produce valid configure and friends.

**Comment by Roguelazer** [comment]
I see the same error locally; I have a valid pkg-config and am running `autoreconf -fi` to regenerate the configure script before building, but I still end up with an invalid configure script that fails with

```
checking dependency style of gcc... gcc3
checking for pandoc... no
configure: WARNING: pandoc not found, man pages rebuild will not be possible
./configure: line 4305: syntax error near unexpected token `bashcompdir,'
./configure: line 4305: `PKG_CHECK_VAR(bashcompdir, bash-completion, completionsdir, ,'
```

`$PKG_CHECK_VAR` was added in pkg-config 0.28, which is a ridiculously new version to depend on and rules out everything CentOS 7 vintage and older.

I might drop a PR to make it backwards-compatible with pkg-config < 0.28.

**Comment by jpmens** [comment]
My apologies for not having caught this earlier; "it compiled on my machines ..." #truestory
