### ISSUE TITLE
Just don't reinvent wheels

### ISSUE THREAD

**Issue by socketpair** [jpmens/jo#108]
`jq` in modern linuxes
`jsonfilter` in OpenWRT
\+ 100500 other tools (like Python pretty-printing)

**Comment by socketpair** [comment]
![image](https://user-images.githubusercontent.com/1157412/68191063-7738c380-ffd0-11e9-8239-4526bb406384.png)

**Comment by socketpair** [comment]
```
$ echo 1 2 3 | jq --slurp '.'
[
  1,
  2,
  3
]
```

and so on

**Comment by mvasilkov** [comment]
Why the negativity though? It's a great little utility with a clear-cut use case.

Why wouldn't there be multiple programs handling a file format, especially a popular one like JSON.

**Comment by hongquan** [comment]
@socketpair But the purpose of jo is to replace those spagetti "echo" command.

**Comment by socketpair** [comment]
Let it be. Every program has its oportunity in the world.
