### ISSUE TITLE
String of "null" becomes empty string ""

### ISSUE THREAD

**Issue by mvasilkov** [jpmens/jo#109]
What I did:
```
$ jo -- -s foo="null"
{"foo":""}
```

What I expected:
`{"foo":"null"}`

Inexplicably I want the word "null" to appear in my JSON. :)

**Comment by jpmens** [comment]
The shell is stripping your quotes. Can you please try ‘“null”’ ?

**Comment by mvasilkov** [comment]
```
$ jo -- -s foo='"null"'
{"foo":"\"null\""}
```

**Comment by kolontsov** [comment]
```
$ jo -B foo=null test=true
{"foo":"null","test":"true"}
```

but -B affects everything, not just next word (as -s)

**Comment by jpmens** [comment]
Jo 1.3 (released recently) allows

```
$ jo foo='\null' test=true
{"foo":"null","test":true}
```
