### ISSUE TITLE
linuxbrew installation failure

### ISSUE THREAD

**Issue by endorama** [jpmens/jo#111]
Hello, when trying to upgrade `jo` from `1.2` to `1.3` using `brew` on Linux I get a permission error when creating bash completion files.

In Homebrew you generally install everything in the Brew prefix (`/home/linuxbrew/.linuxbrew`), but this does not happen for the completion file, which is being created under `/usr/share/bash-completion/completions/` (without proper permissions because `brew` is not running as root).

Reported error is: `/usr/bin/install: cannot create regular file '/usr/share/bash-completion/completions/jo.bash': Permission denied`

I suspect the fix should be applied to the `jo` Homebrew Formula, but how may I specify a different prefix for the completion file? I'm willing to submit PRs to Linuxbrew (and Homebrew as I image that is an issue too) to fix it with some guidance on how to do that.

Thanks!

---

Relevant brew formulas:

https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/jo.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/jo.rb

---

This is the installation log:

```
$ brew upgrade jo
jo 1.2 -> 1.3
==> Upgrading jo 
==> Downloading https://github.com/jpmens/jo/releases/download/1.3/jo-1.3.tar.gz
Already downloaded: /home/[...]/.cache/Homebrew/downloads/41f2360cfe5b1e4639ddc09e727c3a165dd90cdbf459c8575c8b987e4406b673--jo-1.3.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/jo/1.3
==> make install
Last 15 lines from /home/[...]/.cache/Homebrew/Logs/jo/02.make:
mv -f .deps/jo.Tpo .deps/jo.Po
mv -f .deps/json.Tpo .deps/json.Po
gcc-5 -Wall -O2 -g -O2   -o jo jo.o json.o base64.o -lm 
make[1]: Entering directory '/tmp/jo-20200107-31251-1w26r5/jo-1.3'
 /bin/mkdir -p '/home/linuxbrew/.linuxbrew/Cellar/jo/1.3/bin'
 /bin/mkdir -p '/usr/share/bash-completion/completions'
 /bin/mkdir -p '/home/linuxbrew/.linuxbrew/Cellar/jo/1.3/share/man/man1'
 /usr/bin/install -c -m 644 jo.bash '/usr/share/bash-completion/completions'
  /usr/bin/install -c jo '/home/linuxbrew/.linuxbrew/Cellar/jo/1.3/bin'
/usr/bin/install: cannot create regular file '/usr/share/bash-completion/completions/jo.bash': Permission denied
make[1]: *** [Makefile:669: install-dist_bashcompDATA] Error 1
make[1]: *** Waiting for unfinished jobs....
 /usr/bin/install -c -m 644 jo.1 '/home/linuxbrew/.linuxbrew/Cellar/jo/1.3/share/man/man1'
make[1]: Leaving directory '/tmp/jo-20200107-31251-1w26r5/jo-1.3'
make: *** [Makefile:1084: install-am] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by jpmens** [comment]
Thanks for your report, but I'd think you will have to report this to whomever maintains the Homebrew `jo` formula, the links to which you have pasted above.

**Comment by endorama** [comment]
@jpmens thanks for the quick answer!

I will, but as that file is generated by the `make install` I need to now how to address that first I think. (I'm not experienced with Make and it's dialect)

Any hint on how to change the destination folder for bash completion during the make? After I know that I can easily fix the brew Formula.

**Comment by jpmens** [comment]
@endorama the installation bit you are seeing is not from jo's `Makefile` but from the Homebrew formula Makefile.

**Comment by gromgit** [comment]
@endorama The configure script accepts several environment variables, including the following `jo`-specific one:
```
$ ./configure --help
...
Some influential environment variables:
...
  bashcompdir value of completionsdir for bash-completion, overriding
              pkg-config
```
So, it should just be a simple matter of changing the `configure` invocation in the Homebrew formula as follows:
```
bashcompdir=/where/to/put/completions ./configure [...]
```

**Comment by endorama** [comment]
Thanks @gromgit! That works like a charm!

I'll submit a PR straight away to Homebrew. I'm closing this, as the issue does not affect this repository.

Thank you for your time!
