### ISSUE TITLE
Enhancement:  Allow array option to specify delimiter

### ISSUE THREAD

**Issue by scastria** [jpmens/jo#114]
I have a list of strings that have spaces in them.  In order to put them in an array with the -a option, I have to quote the strings.  This is fine on the command line, but when I am using jo in build automation, it can get messy quoting the strings and escaping the quotes, etc.  It would be much easier for me if I could specify a different delimiter than space to separate the values in an array, like:

jo -ad "," -a a,b,c,d,e

where ad stands for array delimiter

**Comment by jpmens** [comment]
```
jo -a “$(echo a,b,c,d,e | sed -e ‘s/,/ /g’)”
```

comes to mind and doesn’t need us adding yet another option to _jo_.

**Comment by scastria** [comment]
But remember my first sentence in my request, "I have a list of strings that have spaces in them."  The sed command will not know which spaces to replace with commas and which are part of the string.  The a,b,c,d,e was just an example of how specifying the delimiter might work.

Perhaps a better example is:

jo -ad "," This is the first string,This is the second string,I have spaces in me,Me too

**Comment by jpmens** [comment]
We can have _jo_ read from _stdin_:

```bash
echo "This is the first string,This is the second string,I have spaces in me,Me too" |
        awk -F, '{for (i = 0; i < NF; i++) { printf "%s\n", $(i+1); } }' |
        jo -a -p

[
   "This is the first string",
   "This is the second string",
   "I have spaces in me",
   "Me too"
]
```

I get your point, but I hope you get mine likewise. :-)

**Comment by scastria** [comment]
Yes, I get your point.  There is always a struggle on how much functionality to put inside a linux utility versus using pipes and redirection from other already existing utilities.  But I would much rather have my users to write:

-ad ","

instead of

echo XXX |
        awk -F, '{for (i = 0; i < NF; i++) { printf "%s\n", $(i+1); } }' |

**Comment by jpmens** [comment]
Wrap it into a shell script for “your users” and you’re done.

I will not implement this because then somebody’s going to want regular expressions as delimiters and whatnot. I believe the Unix toolbox offers sufficient ways to accomplish what you’re after.

If somebody picks this up and has a really really good suggestion as how to implement it, I might consider taking it.

**Comment by scastria** [comment]
I will quote your own document on why your wrote jo:  "I tired of mangling shell scripts to produce JSON".

**Comment by jpmens** [comment]
What exactly are you trying to accomplish by insulting me?
