### ISSUE TITLE
Support empty object {} as value of key

### ISSUE THREAD

**Issue by hongquan** [jpmens/jo#115]
I try to build an [ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started-search.html) query:

```json
{
  "query": { "match_all": {} }
}
```
but jo failed:

```console
$ jo -p query[match_all]=\{\}                                                                                
PANIC: unhandled JSON type 5
{
   "query": {}
}
```

**Comment by scampi** [comment]
It works like this: `jo query=$(jo match_all={})`

**Comment by gromgit** [comment]
> It works like this: `jo query=$(jo match_all={})`

Or in this case: `jq -d . query.match_all={}`

**Comment by hongquan** [comment]
@gromgit 

```console
❯ jq -d . query.match_all={}
jq: Unknown option -d
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```
Thank @scampi, yours solution works, but I still wish a shorter, less symbol command.

**Comment by hongquan** [comment]
@gromgit Turn out that you mistyped "jo" as "jq" and my version of jo is too old (not support "-d" yet).

**Comment by gromgit** [comment]
> Turn out that you mistyped "jo" as "jq"

Whoops. I spend so much time switching between the two... :)

> and my version of jo is too old (not support "-d" yet).

So you're still on 1.1 (or earlier)? That's almost 3 years old at this point, probably time to upgrade. Building from source is very straightforward, see the main page for details.

**Comment by hongquan** [comment]
@gromgit Don't know why Ubuntu repo doesn't contains jo 1.3. I tried to build deb package for jo on Ubuntu infrastructure but failed: https://launchpad.net/~ng-hong-quan/+archive/ubuntu/ppa/+build/18669249

Now I just build on local and install jo 1.3. Your command works. Thanks!

I prefer .deb file to building from source, for easier uninstallation later.

**Comment by hongquan** [comment]
I has successfully built jo 1.3 and published to my PPA: https://launchpad.net/~ng-hong-quan/+archive/ubuntu/ppa
