### ISSUE TITLE
jo adding an extra \ to \\n - Is there a way to stop this?

### ISSUE THREAD

**Issue by hassanbabaie** [jpmens/jo#116]
I'm trying to use the jo tool to produce some JSON files and it's working really well but I'm having an issue with /n within a string.

I'm running the following:

`jo -p title="test" component[name]=HASSAN -s component[version]=1.0 -s description="This request is to test using $SUBMIT_DATE and \n\nTo make it look great:\nthanks" classification=Test`

This then produces:

`
{
   "title": "test",
   "component": {
      "name": "HASSAN",
      "version": "1.0"
   },
   "description": "This request is to test using 10202020 and \\n\\nTo make it look great:\\nthanks",
   "classification": "Test"
}
`

The system I'm sending it to doesn't like the double //n and instead expects /n

However I can;t seem to find a way to have jo stop auto adding the extra /

Any thoughts on this would be great and I really like the tool

Hass

**Comment by gromgit** [comment]
For what you want, you should be passing actual newlines (ASCII 10), not their escaped equivalent (`\n`).

There are at least two ways to do this. One is to put actual newlines in your argument:
```sh
jo -p title="test" component[name]=HASSAN -s component[version]=1.0 -s description="This request is to test using $SUBMIT_DATE and 

To make it look great:
thanks" classification=Test
```
The other is to use the `printf` command to render the escaped newlines for you:
```sh
jo -p title="test" component[name]=HASSAN -s component[version]=1.0 -s description="$(printf "This request is to test using $SUBMIT_DATE and \n\nTo make it look great:\nthanks")" classification=Test
```
Note the quotes around the command substitution (`"$(...)"`). Leave them out, and your shell will happily word-split that argument, and `jo` would be Very Unhappy.

**Comment by hassanbabaie** [comment]
thanks @gromgit I used your second suggestion and that worked perfectly!
