### ISSUE TITLE
leading zeros stripped on my values when they are numeric

### ISSUE THREAD

**Issue by andrewborell** [jpmens/jo#119]
Using jo to create json string for jwt auth and its stripping the leading zeros when they exist in a string containing only numbers.  

`  MY_REQ=$( jo -p agency_id=$AGENCY_ID user_id=$MY_USER password=$MY_PASS )
`

I tried to use % before the variable ( in this case 0636 ) and a message is returned saying "jo: Cannot open 0123 for reading" Even when using % bypassing the variable directly in front of static text I get that error. 

This is one of several places in my scripts that could be affected. Another is where I use FIPS codes, the first 9 of which have leading zeros.  

How can I keep my leading zeros with jo?

**Comment by gromgit** [comment]
You didn't mention which variable was giving you trouble, but from your problem description, I'll assuming it's `$AGENCY_ID`.

This is a job for _type coercion_. Do read that section of the `jo` man page carefully, but here's a quick taster:
```
$ AGENCY_ID=0000123
$ MY_USER=0101011
$ PASSWORD=0000000
$ jo -p -- -s agency_id=$AGENCY_ID user_id=$MY_USER password=$MY_PASS
{
   "agency_id": "0000123",
   "user_id": 101011,
   "password": 0
}
```

**Comment by andrewborell** [comment]
Absolutely brilliant. Thank you for pointing me in the right direction.  Historically I would use % to get this result in bash so I made a poor assumption that all my typical bash tricks were the solution.  My apologies for thinking I was smarter than "_man jo_".
