### ISSUE TITLE
Feature request: add a flag to omit null values from output

### ISSUE THREAD

**Issue by NSExceptional** [jpmens/jo#121]
| Command | Current Behavior | Proposed Behavior |
|:-----------|:------------------|:-------------------|
| `jo foo=`                                | `{"foo":null}` | `{}`
| `jo list[]=1 list[]=$nothing` | `{"list":[1,null]}` | `{"list":[1]}`

I'd like the above to be possible somehow, either with a flag to change the behavior or by specifying a special value or something. Open to anything that allows me to write more dynamically structured JSON without a bunch of this:

```sh
if [[ "$myvar" ]]; then
    jo my-var=$myvar foo=…
else
    jo foo=…
fi
```

Ideally this would be the *default* since that seems more in-line with how bash commands tend to be have, and you could pass a flag to opt-into `null` values:

```sh
jo -n ... make-me-null=
```

**Comment by jpmens** [comment]
I don't think we'd make this the default so as to not break existing invocations, but I'd take a PR which used an option to do as you suggest.

**Comment by jpmens** [comment]
@NSExceptional you are now welcome to test this: @gromgit has added the feature.
