### ISSUE TITLE
Cannot create array if the words start with "--"

### ISSUE THREAD

**Issue by giannikis** [jpmens/jo#127]
All the following commands give errors:
```jo -p -a --test
jo -p -a "--test"
jo -p -a '--test'

jo -p -a -- --test
jo -p -a -- "--test"
jo -p -a -- '--test'

jo -p -a -- -s --test
jo -p -a -- -s "--test"
jo -p -a -- -s '--test'
```

This command works:
```
echo "--test" | jo -p -a
```
but it does not support multiple words (as it considers them a single, space separated word.

The only way I could feed multiple words that start with `--` in an array is the following syntax:
```
echo "--test
--tost" | jo -p -a
```
or the equivalent:
```
echo -e "--test\n--test" | jo -a
```

**Comment by jpmens** [comment]
First, there is no difference in the shells between test, 'test', and "test" -- shells strip the quotes before invoking the program.

I think you're seeing an "feature" of `getopt(3)` (was it the GNU version?) which can have options anywhere in the command line; it permutes them at will, IIRC, and the double dash doesn't do much to help here.

I believe this does what you want:

```bash
$ jo -p -a -- -s \\--test \\--toast
[
   "--test",
   "--toast"
]
```

**Comment by giannikis** [comment]
Thanks for the feedback @jpmens 

Yes, that is GNU and your suggestion works great!

**Comment by gromgit** [comment]
Sorry @jpmens, it's not a `getopt` bug, but a bug in the coercion flag (i.e. my original) code that traps every post-option argument that begins with a dash. I'll fix it so that anything that doesn't look like a coercion flags is taken literally, so `jo -p -a -- --test --toast` should work post-fix.

**Comment by gromgit** [comment]
@giannikis , please upgrade your `jo` and try your test cases out again. Note that `jo -p -a "--test"` still won't work, since `--test` is (correctly) treated as an illegal option.
