### ISSUE TITLE
When reading a large file shell throws "Argument list too long"

### ISSUE THREAD

**Issue by marchenm** [jpmens/jo#132]
`jo -p status=$(jo -a $(jo content=@largefile.txt))` throws "Argument list too long". Is there a way to overcome the limitation without changing the ARG_MAX limit?

**Comment by gromgit** [comment]
For your specific use-case, a temp file does the job, and is also a **LOT** faster when you don't make bash handle huge strings:
```
jo content=@largefile.txt > /tmp/tmp.json
jo -p status[]=:/tmp/tmp.json
```

**Comment by marchenm** [comment]
Makes sense. Thanks for the suggestion!

**Comment by gromgit** [comment]
> `jo content=@largefile.txt > /tmp/tmp.json`
> `jo -p status[]=:/tmp/tmp.json`

Actually, you don't even need a temp file. Process substitution in bash results in a one-liner with no file cleanup required:
```
jo -p status[]=:<(jo content=@largefile.txt)
```
