### ISSUE TITLE
Replacing "null" with an actual null value works as documented

### ISSUE THREAD

**Issue by skoehler** [jpmens/jo#134]
I have a file called `words.txt` with 

```
abc
null
def
```

And `cat words.txt | jo -a -p` creates

```
[
   "abc",
   null,
   "def"
]
```

The command `jo -a -- abc null def` produces the same output.

A similar issue arises if the input data contains `true`, `false`, or something lke `1.23`.

The mission here is very simple: turn a lists of words into a JSON array. If `jo` messes with that list of words in any way, that is evil. The magic that is applied here should be opt-in or opt-out. But I currently see no switch to disable it and it's active by default. So this very simple goal (turning a list of words into a JSON array) cannot be achieved. That seems like a major oversight to me.

Please enhance jo.

**Comment by skoehler** [comment]
Apparently I have to specify `-s` per element, like in
`jo -a -- "abc" "def" -s "null" -s 1.23`

But that somehow defeats the purpose in my case.
In my case, the words are piped in via stdin.

Also bash programmer might want to do something like
`jo -a -- "${WORDARRAY[@]}"` where `WORDARRAY` is a bash array. I see no way of applyin `-s` to all arguments.

**Comment by skoehler** [comment]
Thank you for pointing out `-B`. It also affects `null` even though `jo --help` does not mention it. The man page does mention it, though.
 
Is there something similar for strings like `1` and `1.2` ?

**Comment by jpmens** [comment]
As you've already determined, `-s` coerces to string; you use it per value.

**Comment by gromgit** [comment]
That said, there may be value in an option that turns off type-guessing globally, thereby treating all values as strings. This is especially useful when building arrays from piped input, where prepending `-s ` to numeric inputs has a corruptive rather than coercive effect.

@jpmens, your thoughts?

**Comment by jpmens** [comment]
I don't disagree with you, @gromgit, and we can certainly do that, but I fear we've already passed the point of creeping featurism. 

But by all means go ahead, if you feel like doing it. :-)

**Comment by skoehler** [comment]
> I don't disagree with you, @gromgit, and we can certainly do that, but I fear we've already passed the point of creeping featurism.

I'm not asking for the addition of a feature. I'm asking for a way to disable a feature, that is harmful in my situation. In spite of your intentions, type-guessing actually makes `jo` less useful in my case.

You already provide `-B`, but it leaves type-guessing (type coercion) partially enabled.

I understand why some people may need type-guessing and why you added it. But you have inadvertently introduced ambiguities. And you should allow your users to resolve those the way they need.

> As you've already determined, `-s` coerces to string; you use it per value.

`-s` does not seem to apply to my use-case, which is piped input.

I also mentioned `bash` programming, where passing an array of strings in the command line would clearly be useful (for example: `jo -a -- "${WORDARRAY[@]}"`). When you suggest using `-s`, that would imply that the bash programmer must create a new array which has an `-s` before every word in the array. That is too much work for this simple use-case. A typical workflow would be: use `bash`'s `mapfile` to create the array, then pass it to `jo` in the command line.

My frustration with `jo` is already apparent, I guess. I guess that the tool has grown historically. I would not have imagined that "turn file with strings into JSON array" would not have appeared in the list of use-cases that the tool should cover.

I was planning to use JSON as the input for one of my command line tools. My reasoning was, that it seemed simple to create JSON on the command line. That is an essential prerequisite to integrate the tool into the build process. I currently don't even see a feasible workaround to bypass type-guessing for piped input. Also note that if I had to preprocess the data in bash, then I I would already be half way there to generate JSON myself. Before using `jo`, I must make sure that I avoid any pitfalls such as type-guessing. I must be able to control it, or I cannot use `jo`.

**Comment by jpmens** [comment]
> My frustration with jo is already apparent

I am somewhat heartbroken that our small utility doesn't meet your expectations. </sarcasm> As such  I am now closing this issue.

**Comment by skoehler** [comment]
To whom in may concern, here's is a small python snipped that you can use in your shell script to do the job:
```bash
python3 -c 'import sys, json
a = [ x.rstrip("\n") for x in sys.stdin.readlines() ]
json.dump(a, sys.stdout, indent=2)' \
 < input.txt \
 > output.json
```
