### ISSUE TITLE
[Suggesion] add arg which will prohibit the use of characters to open files

### ISSUE THREAD

**Issue by agent188** [jpmens/jo#138]
%, @, : 
![изображение](https://user-images.githubusercontent.com/41228098/98656438-b7ecba80-2351-11eb-8b73-dd42418e6c82.png)

**Comment by agent188** [comment]
I want these characters to be entered so that the contents of the files do not open, so that these characters do not need to be escaped

**Comment by agent188** [comment]
because if, for example, you make a web component and use jo, you can view the source code simply by setting @ or other similar characters

**Comment by jpmens** [comment]
> make a web component and use jo, you can view the source code simply by setting `@`

I'm not understanding what you mean. Can you illustrate with a short example?

**Comment by agent188** [comment]
Let's imagine that our site backend runs on bash and uses jo to output json. the site has the ability to change the nickname, for example, someone set a nickname @script.sh then all users on the site can see the source code of this script if they go to their profile

**Comment by jpmens** [comment]
It sounds like the data you use needs to be sanitized before use.

**Comment by agent188** [comment]
I cut out the part of the code that was responsible for these characters and compiled it

**Comment by jpmens** [comment]
Closing
