### ISSUE TITLE
Jo 1.4 windows binary

### ISSUE THREAD

**Issue by c33s** [jpmens/jo#139]
would be awesome if you could provide a 1.4 binary for windows.

**Comment by jpmens** [comment]
I've added `jo.exe` to the [release](https://github.com/jpmens/jo/releases/tag/1.4)
Would you please see if it works for you?

**Comment by c33s** [comment]
basic test works

```
λ jo -v
jo 1.4

λ jo -p name=jo n=17 parser=false
{
   "name": "jo",
   "n": 17,
   "parser": false
}
```

thank you very much. this is really an awesome and helpful tool <3
