### ISSUE TITLE
Docker Hub Automated Builld?

### ISSUE THREAD

**Issue by ekristen** [jpmens/jo#142]
Any chance you'd be willing to setup a docker hub automated build tied to your commits and tags? Thanks.

**Comment by jpmens** [comment]
I think we could do that if you're willing to write up exactly what I need to do in order to accomplish that. I have a docker hub account and I've done it before for a different project but I've no recollection of the steps I took. So, if you instruct me how to, I'll press the right buttons. :-)

**Comment by ekristen** [comment]
Awesome @jpmens, here you go.

1. Create an account at https://hub.docker.com/
2. Create Repository, and Name it.
3. Under Build Settings, Link your GitHub Account
4. Under Build Settings, then select the jo repository.
5. Add Build Rule (the defaults for the first are acceptable)
6. Add Second Build Rule, select Source Type to be Tag, Source: `/^[0-9.]+$/`, Docker Tag: `{sourceref}`
7. Create & Build

After this any commits to master will result in a Docker build from the Dockerfile in the root of the directory under the `latest` docker image tag. Any time you push a new tag, it'll result in a docker image with the tag name as the docker tag.

You can once setup, trigger builds for the existing tags, or at least the latest existing 1.4 tag.

**Comment by jpmens** [comment]
Thank you, @ekristen, for the very precise instructions. Everything happened as you indicated it would, which is a relief. 

```console
$ docker run --rm jpmens/jo -v
Unable to find image 'jpmens/jo:latest' locally
latest: Pulling from jpmens/jo
ca3cd42a7c95: Pull complete
ddd9d3ee9638: Pull complete
Digest: sha256:8d2fcd767e49b3a9e5a90341f5a43315b7049d22e508d9d46c646ef5b9eecd72
Status: Downloaded newer image for jpmens/jo:latest
jo 1.4
```

**Comment by ekristen** [comment]
Excellent! Thanks!
