### ISSUE TITLE
Deduplication doesn't work with -f 

### ISSUE THREAD

**Issue by jpmens** [jpmens/jo#144]
We should probably note in the manual somewhere, @gromgit, that deduplication doesn't necessarily go well with `-f`:

```console
$ cat b.json
{
  "name" : "aaa",
  "name" : "aaa"
}

$ ./jo -f b.json name=aaa
{"name":"aaa","name":"aaa","name":"aaa"}

$ ./jo -D -f b.json name=aaa
{"name":"aaa","name":"aaa"}
```

Although I'm leaning toward not even mentioning it ...

**Comment by gromgit** [comment]
Hmmm, that's a corner case I hadn't thought about. Deduplication currently happens at the `jo` level, but loading existing JSON context happens at a lower level, in `json_decode`. I'll work on a fix, seems simple enough.
