### ISSUE TITLE
how to output string start with at sign `@`?

### ISSUE THREAD

**Issue by GHolk** [jpmens/jo#153]
Hi, I just notice this tool, it is awesome!
However, is it possible to produce json with some attribute string starting with `@`?
I am tuning my [matrix](https://matrix.org) server, and the matrix username is in `@user:server.domain` form,
so I have to produce json like `{"m.room.member":"@user:server.io"}` .

I tryed `jo m.room.member=@user:server.io` , but jo would try to open file `user:server.io`.
I know it is possible to  store the username in file and use `@` to include it,
but it is troublesome.

How about allow `\x40` or `\u0040`?
or use a switch instead of at sign to indicate jo reading from file? like `jo -r foo=file` instead of `jo foo=@file`

**Comment by gromgit** [comment]
From the man page:
>```
>       @file   substitute the contents of file as-is
>[...]
>       Escape the special character with a backslash to prevent this interpretation.
>```

So:
```bash
# Quote a single backslash to avoid your shell interpreting it
$ jo m.room.member="\@user:server.io"
{"m.room.member":"@user:server.io"}

# Or simply double it up 
$ jo m.room.member=\\@user:server.io
{"m.room.member":"@user:server.io"}
```

**Comment by GHolk** [comment]
thank you. It seem that the debian version 1.0 does support this.

```term
~ $ jo -v
jo 1.0
~ $ jo m.room.member=\\@foo
{"m.room.member":"\\@foo"}
```
