### ISSUE TITLE
how to specify literally "backslash with t" as a key value

### ISSUE THREAD

**Issue by tg0h** [jpmens/jo#154]
<img width="433" alt="screenshot_2021-07-06T14 39 20_iTerm2-tim@moopy~devworkingabsabsauthentication" src="https://user-images.githubusercontent.com/7954426/124553953-fb0f1700-de67-11eb-9618-5d983b3e2a35.png">
hello,

how do i create a json object with '\t' as a key value?

- Current:
  - Currently when i specify '\t',  the backslash \ disappears.
  - When I specify backslash backslash t '\\\t', the backslash appears twice
- Expected:
  - I would like to create a json object with '\t' as the key value

**Comment by tg0h** [comment]
oops, I see that this is very similar to #116 , i will study the answer to see if that solves my problem

**Comment by gromgit** [comment]
Aside from the `printf` solution I mentioned in #116, bash (and I think zsh too) has a specific syntax for C-style escape expansions:
> Words of the form `$'string'` are treated specially.  The word expands to _string_, with backslash-escaped characters replaced as specified by the ANSI C standard.  Backslash escape sequences, if present, are decoded as follows:
> [...]
> `\t`     horizontal tab

So:
```
$ jo test=$'\t'
{"test":"\t"}
```
NOTE: Anything that consumes `{"test":"\t"}` _and_ implements the [JSON spec](https://www.json.org/) strictly will interpret that value as a 1-character string that is a _horizontal tab_ (i.e. the control character with ASCII value 10), **not** a 2-character string whose first character is a backslash and the second is the letter `t`. If you actually intended the latter, then you really want to generate `{"test":"\\t"}` instead.

**Comment by tg0h** [comment]
Thank you, turns out i wanted to send the control character with ASCII value 10, not a literal \t and therefore $'\t' fixed it. I did not know i could do this in bash/zsh 🙏
