### ISSUE TITLE
File is not included in json - "No such file or directory"

### ISSUE THREAD

**Issue by LumpiStefan** [jpmens/jo#155]
Hello.

I´ve got an issue with the use of jo to include an existing file to a json. The file should be base64 encoded.
As a first try i run:
jo filename=/tmp/decoded-20210803215054.png content=%/tmp/decoded-20210803215054.png

As result i get:
/tmp/decoded-20210803215054.png: No such file or directory
jo: Cannot open /tmp/decoded-20210803215054.png for reading

But the file is existent:
system1558:/tmp# ls -ltr /tmp/decoded-20210803215054.png
-rw-r--r-- 1 root root 554185 Aug  3 23:51 /tmp/decoded-20210803215054.png

Is that an issue, where is the problem?
I want to include a file in base64-format to an json. 
If i provide the base64 encoded content directly to the jo caommand, i get: /snap/bin/jo: Argument list too long

Help is welcome

Stefan

**Comment by jpmens** [comment]
Are you sure the file actually exists?

```console
$ echo hello > /tmp/hi
$ jo content=%/tmp/hi
{"content":"aGVsbG8K"}
```

**Comment by LumpiStefan** [comment]
Does not work for me:
system1558:~# echo hello > /tmp/hi
system1558:~# jo content=%/tmp/hi
/tmp/hi: No such file or directory
jo: Cannot open /tmp/hi for reading
system1558:~#

system1558:~# jo -v
jo 1.4

**Comment by LumpiStefan** [comment]
I installed jo by: snap install jo

On another system it is working:
stefan@linux-station:~$ sudo apt-get install jo
stefan@linux-station:~$ jo -v
jo 1.0
stefan@linux-station:~$ echo hello > /tmp/hi
stefan@linux-station:~$ jo content=%/tmp/hi
{"content":"aGVsbG8K"}

An issue with version 1.4?

**Comment by B-Art** [comment]
Posibly SeLinux issue?

**Comment by B-Art** [comment]
> I installed jo by: snap install jo
> 
> On another system it is working:
> 
> ```
> stefan@linux-station:~$ sudo apt-get install jo
> stefan@linux-station:~$ jo -v
> jo 1.0
> stefan@linux-station:~$ echo hello > /tmp/hi
> stefan@linux-station:~$ jo content=%/tmp/hi
> {"content":"aGVsbG8K"}
> 
> stefan@linux-station:~$ sudo apt-get remove jo
> stefan@linux-station:~$ git clone git://github.com/jpmens/jo.git
> stefan@linux-station:~$ cd jo
> stefan@linux-station:~$ autoreconf -i
> stefan@linux-station:~$ ./configure
> stefan@linux-station:~$ make check
> stefan@linux-station:~$ sudo make install
> stefan@linux-station:~$ cd ..
> stefan@linux-station:~$ echo hello > /tmp/hi
> stefan@linux-station:~$ /usr/local/bin/jo content=%/tmp/hi
> {"content":"aGVsbG8K"}
> ```
> 
> So it looks like an issue with the snapd installed version....

SeLinux Enabled?

**Comment by B-Art** [comment]
> Does not work for me:
> 
> ```
> system1558:~# echo hello > /tmp/hi
> system1558:~# jo content=%/tmp/hi
> /tmp/hi: No such file or directory
> jo: Cannot open /tmp/hi for reading
> system1558:~#
> 
> system1558:~# jo -v
> jo 1.4
> 
> system1558:~# ls -ltr /tmp/hi
> -rw-r--r-- 1 root root 6 Aug  4 00:25 /tmp/hi
> ```

Posibly SeLinux enabled?

**Comment by jpmens** [comment]
I've not heard of `/tmp/` being under SeLinux control, but you'll have to verify.

**Comment by jpmens** [comment]
Closing
