### ISSUE TITLE
Issue with floating point precision

### ISSUE THREAD

**Issue by erhhung** [jpmens/jo#156]
I'm getting undesired floating point precision on the output compared to `jq` and `node`:

```bash
$ jo x=73.152 y=73.155
{"x":73.152,"y":73.155}

$ jo x=73.153 y=73.156
{"x":73.15300000000001,"y":73.15600000000001}

$ jq -nc '{x:73.153, y:73.156}'
{"x":73.153,"y":73.156}

$ jo x=73.153 y=73.156 | jq -c
{"x":73.153,"y":73.156}

$ node -e 'console.log(JSON.stringify({x:73.153, y:73.156}))'
{"x":73.153,"y":73.156}

$ jo -v
jo 1.4
```

**Comment by jpmens** [comment]
I don't think there's very much we can do about this. The underlying `json.c` uses this in its `emit_number()` function, and other than making that configurable (which I don't think we should do), I don't see how we can change the behavior of floating point numbers:

```c
snprintf(buf, sizeof(buf), "%.16g", num);
```

**Comment by jpmens** [comment]
This is off topic because it's a different language, but as long as this kind of thing happens in programming languages, I think we'll continue the long ride. ;-)

```console
$ python3
Python 3.9.0 (default, Dec  6 2020, 18:02:34)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.1 + 0.2
0.30000000000000004
>>>
```

**Comment by jpmens** [comment]
Closing as we can't really do much about this.
