### ISSUE TITLE
Build List within json 

### ISSUE THREAD

**Issue by LumpiStefan** [jpmens/jo#157]
Hello Community.

I need some help with the "jo" command.
I´m trying to build a JSON structure with jo like this:

```json
{
"Ticket":{
        "Title":"REST Create Test",
        "CustomerUser":"customer"
      }
,"Article":{
        "Subject":"Test Subject",
        "Body":"This is only a test"
        }
,"Attachment":[
             {
            "ContentType":"image/gif",
             "Filename":"img1.gif"
           }
            ,{
             "ContentType":"image/gif",
             "Filename":"img2.gif"
         }
      ]
}
```

I have already handled it to build it with a single entry in Attachment:

```console
/snap/bin/jo -p -d. "Ticket.Title"="REST Create Test" "Ticket.CustomerUser"="customer" "Article.Subject"="Test Subject" "Article.Body"="This is only a test" "Attachment.ContentType"="image/gif" "Attachment.Filename"="img1.gif" 
```

```json
{
  "Ticket": {
     "Title": "REST Create Test",
     "CustomerUser": "customer"
  },
  "Article": {
     "Subject": "Test Subject",
     "Body": "This is only a test"
  },
  "Attachment": {
     "ContentType": "image/gif",
     "Filename": "img1.gif"
  }
}

```

But how can i add a second entry / list of entries for additional attachments?
In the examples I have seen how to create a list with single entries, but for the attachment i need several values.... :-(

Any help is welcome...

Best regards

Stefan

**Comment by LumpiStefan** [comment]
Looks like I have the solution....
`jo -p -d. "Ticket.Title"="REST Create Test" "Ticket.CustomerUser"="customer" "Article.Subject"="Test Subject" "Article.Body"="This is only a test" Attachments=$(jo -a $(jo "ContentType"="image/gif" "Filename"="img1.gif") $(jo "ContentType"="image/gif" "Filename"="img1.gif"))`

And the result is:

```
{
   "Ticket": {
      "Title": "REST Create Test",
      "CustomerUser": "customer"
   },
   "Article": {
      "Subject": "Test Subject",
      "Body": "This is only a test"
   },
   "Attachments": [
      {
         "ContentType": "image/gif",
         "Filename": "img1.gif"
      },
      {
         "ContentType": "image/gif",
         "Filename": "img1.gif"
      }
   ]
}
```


Stefan

**Comment by LumpiStefan** [comment]
I still have an issue, in this case it is based on the list, so I keep it in this issue.
Besides the given values i also want to include the files. therefore  I use the command:
`jo -p -d. "Ticket.Title"="REST Create Test" "Ticket.CustomerUser"="customer" "Article.Subject"="Test Subject" "Article.Body"="This is only a test" Attachments=$(jo -a $(jo "ContentType"="image/gif" "Filename"="img1.gif" "Content"=%/tmp/file-1) $(jo "ContentType"="image/gif" "Filename"="img1.gif" "Content"=%/tmp/file-2))`

Since the content is already encoded in the nested jo command, this ends up with error: "Argument list too long"

Any idea in this case?

Stefan

**Comment by jpmens** [comment]
What you're trying to do is likely too much for `jo` respectively too much in terms of nesting in the shell, etc.

Furthermore there's nothing you can do (besides recompiling your Unix/Linux kernel) to rid yourself of the "Argument list too long" error: Unix has a maximum number of characters (IIRC `ARG_MAX` in `limits.h`) you cannot overcome.

I think it's time to use a language with which you can correctly create JSON from your data.

I am now closing this issue.

**Comment by gromgit** [comment]
While I agree with @jpmens that this is better done in a JSON-enabled language, you _can_ construct what you want from the bash command line, and without tripping any command-line length limits. The secret sauce is a combination of bash's [process substitutions](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html) and `jo`'s array-append syntax:
```
jo -p -d. "Ticket.Title"="REST Create Test" "Ticket.CustomerUser"="customer" \
  "Article.Subject"="Test Subject" "Article.Body"="This is only a test" \
  Attachments[]=:<(jo "ContentType"="image/gif" "Filename"="img1.gif" "Content"=%/tmp/file-1) \
  Attachments[]=:<(jo "ContentType"="image/gif" "Filename"="img2.gif" "Content"=%/tmp/file-2)
```
