### ISSUE TITLE
Issue jo package in ubuntu 14.04

### ISSUE THREAD

**Issue by davidsugianto** [jpmens/jo#159]
Does this `jo` not exist in ubuntu 14.04 ? because i installed via APT it doesn't exist. 

```
root@257546a680df:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
root@257546a680df:/# apt install jo -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package jo
```

**Comment by jpmens** [comment]
I cannot say wether it does or doesn't exist. If the system cannot locate the package `jo` it likely hasn't been ported / packaged, but you should be able to build it from source if that's an option.

**Comment by jpmens** [comment]
Instructions for building are in the [README](https://github.com/jpmens/jo). Let us know if you run into trouble doing so.
