### ISSUE TITLE
Assertion failure when both inserting and using as a key/value

### ISSUE THREAD

**Issue by isidentical** [jpmens/jo#160]
The following script produces an assertion error;
```
root@43b8b7fd910a:/# jo b[]=1 b[a]=3
jo: json.c:591: json_append_member: Assertion `object->tag == JSON_OBJECT' failed.
Aborted (core dumped)
```

Version:
```
root@43b8b7fd910a:/# jo -v
jo 1.3
```

**Comment by jpmens** [comment]
Thanks for the report. Occurs in 1.4 as well.

**Comment by gromgit** [comment]
It's technically doing the right thing, since `b[]=1` creates an 1-element array, which `b[a]=3` then tries to append to as an object. I suppose it just needs a friendly error message instead of an ugly assert.

**Comment by isidentical** [comment]
> I suppose it just needs a friendly error message instead of an ugly assert.

Indeed. It was just unexpected to get an abort instead of a proper error.
