### ISSUE TITLE
[SUGGESTION] -a give list of str instead of list of words.

### ISSUE THREAD

**Issue by JohnLErvin** [jpmens/jo#161]
**jo 1.4**

` jo -p countries=$(jo -a Germany Switzerland United Kingdom) `

Will give four countries. Would be nice is the following worked to give only three.

` jo -p countries=$(jo -a "Germany" "Switzerland" "United Kingdom") `

The following also does not work to give three countries:

` jo -p countries=$(jo -a Germany Switzerland United\ Kingdom) `

Curiously the following does work to give a list of three when standing alone:
`jo -a Germany Switzerland United\ Kingdom`

**Comment by gromgit** [comment]
Bash performs word splitting and pathname expansion on the results of command substitutions. To avoid that, simply quote the substitution itself:
```
$ jo -p countries="$(jo -a "Germany" "Switzerland" "United Kingdom")"
{
   "countries": [
      "Germany",
      "Switzerland",
      "United Kingdom"
   ]
}
```

**Comment by JohnLErvin** [comment]
Thanks @gromgit!
