### ISSUE TITLE
Gaps in variable

### ISSUE THREAD

**Issue by tom-i** [jpmens/jo#182]
Hi,
if `vod_title_original` **has some gaps (spaces) inside** `jo` doesn't add whole string with gaps, just first string.

```
vod_title_original='The Dawns Here Are Quiet'
jo -p -n  -- -s id=$vod_id name="$vod_title" meta[alternativeName]=$(jo name="$vod_title_original")
```

result: 
```
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "meta": {
      "alternativeName": "{\"name\":\"The",`
....
```

Without quotes:
`jo -p -n  -- -s id=$vod_id name="$vod_title" meta[alternativeName]=$(jo name=$vod_title_original)`
```
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "meta": {
      "alternativeName": {
         "name": "The"
       },
....
```
Looks like bug for me, or have I misunderstood something? Because basic element `name:` shows gaps without problem.

**Distro**: Archlinux
**jo**: 1.6

**Comment by gromgit** [comment]
You've misunderstood bash command line expansion. From [the EXPANSION section of the bash man page](https://man7.org/linux/man-pages/man1/bash.1.html#EXPANSION):

> Expansion is performed on the command line after it has been split into words.  There are seven kinds of expansion performed: brace expansion, tilde expansion, parameter and variable expansion, command substitution, arithmetic expansion, word splitting, and pathname expansion.
>
> The order of expansions is: brace expansion; tilde expansion, parameter and variable expansion, arithmetic expansion, and command substitution (done in a left-to-right fashion); word splitting; and pathname expansion.

Note that command substitution comes _before_ word splitting. In fact, you left out some errors in your original output, that were a Big Red Flag waving you in this direction:
```bash
$ vod_id="1611180934340500000"
$ vod_title="…a jitra jsou zde tichá"
$ vod_title_original='The Dawns Here Are Quiet'

$ jo name="$vod_title_original"
{"name":"The Dawns Here Are Quiet"}

$ jo -p -n  -- -s id=$vod_id name="$vod_title" meta[alternativeName]=$(jo name="$vod_title_original")
Argument `Dawns' is neither k=v nor k@v
Argument `Here' is neither k=v nor k@v
Argument `Are' is neither k=v nor k@v
Argument `Quiet"}' is neither k=v nor k@v
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "meta": {
      "alternativeName": "{\"name\":\"The"
   }
}
```
You just need another pair of quotes, to protect your command substitution against word splitting:
```bash
$ jo -p -n  -- -s id=$vod_id name="$vod_title" meta[alternativeName]="$(jo name="$vod_title_original")"
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "meta": {
      "alternativeName": {
         "name": "The Dawns Here Are Quiet"
      }
   }
}
```

**Comment by tom-i** [comment]
Thx a lot.. helped :+1:
