### ISSUE TITLE
Delete nested element

### ISSUE THREAD

**Issue by tom-i** [jpmens/jo#183]
Hi again :-)
I have some weird stuff and I would like to know, how to solve this with `jo`.
I have 2 situations with these 2 variables:
1. `vod_csfd=https://www.csfd.cz/film/408233-a-jitra-jsou-zde-ticha/prehled/` and `vod_csfd_id=film/408233`
2. `vod_csfd=""` and `vod_csfd_id=""`

I'm using this call:
```
jo -p -n  -- -s id=$vod_id name="$vod_title" type=$vod_type \
        seasonNumber=$vod_seasonNumber episodeNumber=$vod_episodeNumber \
        meta[links]=$(jo csfd=$(jo -n dbId=$vod_csfd_id link=$vod_csfd)) \
```

1. is fine, if that variables have some inside, it should looks like this
```
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "type": "movie",
   "meta": {
      "links": {
         "csfd": {
            "dbId": "film/408233",
            "link": "https://www.csfd.cz/film/408233-a-jitra-jsou-zde-ticha/prehled/"
          }
       }
    },
},
```

2. is this:
```
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "type": "movie",
   "meta": {
      "links": {
         "csfd": {}
       }
    },
},
```
But I wanted to looks like this, so without `"csfd": {}`
```
{
   "id": "1611180934340500000",
   "name": "…a jitra jsou zde tichá",
   "type": "movie",
   "meta": {
      "links": {}
    },
},
```

**Comment by jpmens** [comment]
`jo` cannot transform JSON; you'll want to look at other tools for that, e.q. `jq`.

**Comment by gromgit** [comment]
Or simply let bash do the heavy lifting:
```bash
# Figure out what the "links" value should look like...
if [[ -n $vod_csfd && -n $vod_csfd_id ]]; then
  meta_links=$(jo csfd="$(jo -n dbId="$vod_csfd_id" link="$vod_csfd")")
else
  meta_links={}
fi
# ...then substitute it in
jo -p -n  -- -s id="$vod_id" name="$vod_title" type="$vod_type" \
        seasonNumber="$vod_seasonNumber" episodeNumber="$vod_episodeNumber" \
        meta[links]="$meta_links"
```

**Comment by tom-i** [comment]
> Or simply let bash do the heavy lifting:
> 
> ```shell
> # Figure out what the "links" value should look like...
> if [[ -n $vod_csfd && -n $vod_csfd_id ]]; then
>   meta_links=$(jo csfd="$(jo -n dbId="$vod_csfd_id" link="$vod_csfd")")
> else
>   meta_links={}
> fi
> # ...then substitute it in
> jo -p -n  -- -s id="$vod_id" name="$vod_title" type="$vod_type" \
>         seasonNumber="$vod_seasonNumber" episodeNumber="$vod_episodeNumber" \
>         meta[links]="$meta_links"
> ```

Aha.. so it's not possible to do it via `jo`. Okay..
I thought to do it in BASH, but still hope that `jo` can handle it. :-/

**Comment by gromgit** [comment]
> I need to know how jo can handle deleting `csfd` element inside `links`

Deleting _is_ transforming. `jo` is an _additive_ tool; subtracting or otherwise changing JSON elements is not in its scope.
