### ISSUE TITLE
Suberflous `\` if try to escape `}` in value

### ISSUE THREAD

**Issue by hikhvar** [jpmens/jo#187]
Hello, 

I want to encode some JSON as string value. Therefore I used the trick to escape both the leading `{` and the trailing `}` with an `\` like this: 

```
jo foo='\{"bla":"blub"\}'
{"foo":"{\"bla\":\"blub\"\\}"

 jo foo='\{"bla":"blub"\}' -p | jq .foo
"{\"bla\":\"blub\"\\}"
```

As you can see, jo adds two `\\` for the trailing `}`

My expected result would have been:
```
 jo foo='\{"bla":"blub"\}' -p | jq .foo
"{\"bla\":\"blub\"}"
```

If only the leading `{` is escaped, `jo` detects the value as nested object:
```
jo foo='\{"bla":"blub"}' -p
{
   "foo": {
      "bla": "blub"
   }
}
```

Jo Version:
```
jo -v
jo 1.6
```

**Comment by jpmens** [comment]
You are not showing us exactly what you get (e.g the diagnosting warning):

```console
$ jo foo='\{"bla":"blub"\}' -p
Argument `-p' is neither k=v nor k@v
{"foo":"{\"bla\":\"blub\"\\}"}
```

This is probably not a bug but simply an esacaping thing. I think you'll find this solves your task:

```console
$ jo bla=blub > /tmp/f
$ jo  foo=@/tmp/f | jq .
{
  "foo": "{\"bla\":\"blub\"}"
}
```

**Comment by gromgit** [comment]
>```
>jo foo='\{"bla":"blub"\}'
>```
`jo` can just as easily do that for you in a sane way, with nested invocations and (very ***VERY*** important) proper quoting of each value:
```bash
$ jo -p foo="$(jo bla=blub)"
{
   "foo": {
      "bla": "blub"
   }
}

$ jo -p foo="$(jo bar="$(jo baz="$(jo -a 42 78 hike)")" flurb=tens)"
{
   "foo": {
      "bar": {
         "baz": [
            42,
            78,
            "hike"
         ]
      },
      "flurb": "tens"
   }
}
```

**Comment by hikhvar** [comment]
> You are not showing us exactly what you get (e.g the diagnosting warning):

That is not true, maybe my build (binary package from Archlinux) is broken, but I don't get any diagnostics warning here. 

![jo](https://user-images.githubusercontent.com/263448/190145501-d3a0e66e-89f3-4d9c-9a80-1396048a64db.gif)


@gromgit as @jpmens said, I want to have the string instead of the nested object. 

@jpmens I don't understand why this odd escaping behaviour isn't a bug? I double checked it with both `zsh` and `bash`, both of the time the escaping seems to get broken within jo.

**Comment by gromgit** [comment]
Sorry, I misunderstood. Still, assuming you want  `{"bla": "blub"}` to be treated as a string, `jo` has allowed string coercions for a long time now:
```bash
$ jo -p -- -s foo='{"bla": "blub"}'
{
   "foo": "{\"bla\": \"blub\"}"
}

 jo -p -- -s foo="$(jo bla=blub)"
{
   "foo": "{\"bla\":\"blub\"}"
}
```
Note that the first example actually preserved the space after the colon, proving conclusively that the value was indeed treated as a string instead of being interpreted by `jo`.

**Comment by jpmens** [comment]
I invented `jo`, but @gromgit remains the person who knows it best. Thank you, Adrian.

**Comment by hikhvar** [comment]
ok, sorry, I tried with `jo -s foo='{"bla": "blub"}'` first, but only got the message 

```
jo: invalid option -- 's'
[...help...]
```

Should have read the manual more in depth.

**Comment by TimDeve** [comment]
Sorry for the comment on a closed issue but I thought it might be helpful to people finding this issue.
A more streamline way is to use the shell "process substituion" or `<()`:
```shell
jo foo=@<(jo bla=blu)
```
