### ISSUE TITLE
feature allow string vals with spaces deep nested

### ISSUE THREAD

**Issue by camerondavison** [jpmens/jo#188]
# 1
```
❯ jo a=$(jo foo=bar)
{"a":{"foo":"bar"}}
```

# 2
```
❯ jo a=$(jo foo='bar baz')
Argument `baz"}' is neither k=v nor k@v
{"a":"{\"foo\":\"bar"}
```

# 3
```
❯ jo a="$(jo foo='bar baz')"
{"a":{"foo":"bar baz"}}
```

I like that it is easy to nest json objects arbitrarily deep even without have to bash string quote stuff a lot. But I want option 2 to work. I can get it to work by quoting it, but then that seems to force me to quote everything all the way up.

**Comment by gromgit** [comment]
> But I want option 2 to work.

Get used to "quoting all the values". It's your (and everyone else's) _shell_ that's doing the word-splitting; `jo` can't do anything about that.
