### ISSUE TITLE
UTF-8 crash - `Assertion failed: (utf8_validate(str))`

### ISSUE THREAD

**Issue by nikcorg** [jpmens/jo#191]
Adding on to the already reported issues #53 and #184, I have also come to experience utf-8 anger:

```
Assertion failed: (utf8_validate(str)), function emit_string, file json.c, line 1209.
Abort trap: 6
```

I have a script which pulls down some data from [geonames.org](https://download.geonames.org/export/dump/), groups the data using SQLite3 and then attemps to compile the data into json format with the kind help of jo.

Funnily enough, jo touches the data a few times; a first pass to produce the distinct objects (which involves jo twice) and a final time to pile them all up as an array. The first pass works fine, but the final step bundling the disparate objects into an array produces the above error.

It could be related to jo's type inference/guessing. It looks like it on occasion is unable to spot that the input data is json. (I couldn't see a flag to force the type.)

```
$ jo -v
jo 1.6
```

To reproduce the utf-8 crash: grab input data from https://gist.githubusercontent.com/nikcorg/a7651dc75a4e5019b37cbbc35790cc59/raw/f9faa198ff79e300caacb4cd413226c7761c800d/utf-8-crash.json and reproduce with `jo -a < utf-8-crash.json`.

To reproduce bad type inference: grab input data from https://gist.githubusercontent.com/nikcorg/a7651dc75a4e5019b37cbbc35790cc59/raw/4c407f1ce9aff4f79ee46432ad8b2defaf0ce935/bad-inference.json and reproduce with `jo -a < bad-inference.json`

**Comment by gromgit** [comment]
I can replicate both your issues on macOS. `jo` on Linux handles `bad-inference.json` just fine:
```
linux$ jo -a < bad-inference.json
[{"timezone":"Africa/Algiers","cities":["Abou el Hassan"...
```
but treats `utf-8-crash.json` as a string:
```
linux$ jo -a < utf-8-crash.json
["{\"timezone\":\"Asia/Kolkata\",\"cities\":[\"Abhayāpuri\",\"Abohar\",...
```
So something's hinky here, but the stopgap solution is already documented in the `jo` man page:
```
jo normally treats value as a literal string value, unless it begins with one of the following characters:

value   action
──────────────────────────────────────────────────────────────────────────
@file   substitute the contents of file as-is
%file   substitute the contents of file in base64-encoded form
:file   interpret the contents of file as JSON, and substitute the result
```
`jo -a :utf-8-crash.json` and `jo -a :bad-inference.json` work exactly as advertised on both Linux and macOS.

**Comment by nikcorg** [comment]
That may well be, but that's not how this data is being passed to jo in my use case. It's only written to a file so that was able to pass provide the data here. The data is being piped to jo and both examples are just a single record in a big pile of similar ones.

That said, I'd be happy to ingest the data via a tempfile on disk, but because it isn't be a valid json file (it's a json object per line), jo refuses to ingest it.

Here's what the loop which generates the json looks like, to give you a better idea of my use case:

```
while IFS="|" read -r timezone cities; do
	jo timezone="$timezone" \
	   cities="$(while read -rd ";" city; do echo "$city"; done <<<"${cities};" | jo -a)"
done < "$sqlite_out" | jo -a > "$json_out"
```

**Comment by jpmens** [comment]
@nikcorg we’ve just merged a patch by @gromgit which addresses reading long lines in `jo`. Would you like to see if this fixes your use-case?

**Comment by nikcorg** [comment]
Yes it does. Thank you both very much :-)
