### ISSUE TITLE
Dynamic array of nested oneofs

### ISSUE THREAD

**Issue by mfridman** [jpmens/jo#200]
Apologies if there's an issue (or example) that satisfies this, but I failed to find a [similar example in jo.md](https://github.com/jpmens/jo/blob/master/jo.md) and/or issue.

I'd like to express this with `jo`, any suggestions would be welcome:

```json
{
    "foo": [
        {
            "name": "bar"
        },
        {
            "id": "e361d207-2345-4770-8c44-e9487615217d"
        },
        {
            "id": "bb344cab-94cc-47e0-a329-621e64ab6612"
        }
    ]
}
```

The closest I've gotten was:

```
jo foo=$(jo -a name='bar' id='e361d207-2345-4770-8c44-e9487615217d' id='bb344cab-94cc-47e0-a329-621e64ab6612')

{"foo":["name=bar","id=e361d207-2345-4770-8c44-e9487615217d","id=bb344cab-94cc-47e0-a329-621e64ab6612"]}
```

But, this gives me an array of k/v (words), whereas I'd like **an array of objects**.

### EDIT:

I guess it's `jo` all the way down, is there a more elegant solution?

```
jo foo=$(jo -a $(jo name='bar') $(jo id='e361d207-2345-4770-8c44-e9487615217d') $(jo id='bb344cab-94cc-47e0-a329-621e64ab6612'))
```

**Comment by gromgit** [comment]
Sorry, no. Nesting `jo` invocations is exactly what you need to do, or use temp variables to store intermediate components.
