### ISSUE TITLE
Disable type coercion 

### ISSUE THREAD

**Issue by marbon87** [jpmens/jo#204]
Hi, 

i am using jo to transform a list of key-value-pairs to json.
I want to disable the type coercion because the value always must be a string for the api.

My problem is that i cannot use 

`jo -- -s foo=123`

because the parameters are determined dynamically and i need to use this format:

`echo 'foo=123'  | jo` 

The `-s` Notation is not working for that. How can i complete disable type coercion?

**Comment by marbon87** [comment]
Unfortunately i cannot use that variant because i have nested json objects with whitespaces in the values and that does not work correctly for some reasons.

**Comment by jpmens** [comment]
Have you tried quoting the shell variable "$(  )"

**Comment by marbon87** [comment]
Yes, does not work for me. My script looks like this:

```
#!/usr/bin/env bash
set -o pipefail
set -o nounset
set -o xtrace

INPUT_PARAMETER="
first=Hello World
second=Foo Bar
"
JO_PARAMETERS="id=1"

if [[ "${INPUT_PARAMETER}" == *"="* ]]; then
  while IFS= read -r line; do
      IFS='=' read -a keyValuePair <<< "${line}"
      if [ ! -z "${keyValuePair:-}" ]; then # Leere Zeilen ignorieren
        key=${keyValuePair[0]}
        value="${keyValuePair[1]}"

        echo ">> key: '${key}' value: '${value}'"
        JO_PARAMETERS+="\n${key},value=${value}"
      fi
  done <<< ${INPUT_PARAMETER}
fi

echo -e "${JO_PARAMETERS}" | jo -p -d,
jo -p -d, ${JO_PARAMETERS}
```

**Comment by gromgit** [comment]
> I want to disable the type coercion because the value always must be a string for the api.

That sounds like you want to _force_ type coercion, not disable it.

For the general problem you're facing (assembling JSON from dynamic input), shell arrays are your friend. Here's a simplified rewrite of your example, including a numeric value (which you said should be coerced to a string for API consumption):
```bash
#!/usr/bin/env bash
INPUT_PARAMETER="
first=Hello World
second=Foo Bar
third=123
"
JO_PARAMETERS=("id=1")

while read -r line; do
  if [[ $line =~ (.*)=(.*) ]]; then
    key=${BASH_REMATCH[1]}
    value=${BASH_REMATCH[2]}
    echo ">> key: '${key}' value: '${value}'"
    JO_PARAMETERS+=("${key}=$(jo -- -s value="${value}")")
  fi
done <<<"${INPUT_PARAMETER}"

jo -p "${JO_PARAMETERS[@]}"
```
and here's what happens when you run it:
```
$ bash test.sh
>> key: 'first' value: 'Hello World'
>> key: 'second' value: 'Foo Bar'
>> key: 'third' value: '123'
{
   "id": 1,
   "first": {
      "value": "Hello World"
   },
   "second": {
      "value": "Foo Bar"
   },
   "third": {
      "value": "123"
   }
}
```
