### ISSUE TITLE
possible bug: use of `-a` on outer command in nested jo fails to render inside object element when space exists in internal object property value

### ISSUE THREAD

**Issue by notjames** [jpmens/jo#205]
Oof...tough to craft a meaningful title for this.

So, I'm attempting to craft a JSON string array of objects, though in my case, there's only one object.

### Sample Data

example JSON I'm trying to `jo`-ize:
```json
[{
    "status": "firing",
    "labels": {
      "alertname": "test-alert",
      "service": "test alert",
      "severity":"warning",
      "routing_key": "somekey",
      "alert_type" : "node",
      "node_name": "nonexistent",
      "namespace": "nonexistent",
      "instance": "test-alert.example.net"
    },
    "annotations": {
      "summary": "THIS IS A TEST ALERT"
    },
    "generatorURL": "http://prometheus.int.example.net/<generating_expression>"
  }]
```

I've been through several permutations of this, which probably should work, but every attempt failed rendering with strange results. The main issue is that internal objects always get truncated and/or rendered as a string instead of the expected object key-value pairs. 

### Initial Finding

I first started with crafting a `jo` command which I thought would work, but it didn't. Some permutations I tried:

```bash
✦2 at 17:21:48 ❯ jo -a "$(jo labels="$(jo alertname="test-alert" service="test alert" severity="warning" routing_key="somestring" alert_type="node" node_name="none" namespace="nonexistent" annotations="$(jo summary="some summary")" instance="some-instance")"))"
```
```json
["{\"labels\":{\"alertname\":\"test-alert\",\"service\":\"test alert\",\"severity\":\"warning\",\"routing_key\":\"somestring\",\"alert_type\":\"node\",\"node_name\":\"none\",\"namespace\":\"nonexistent\",\"annotations\":{\"summary\":\"some summary\"},\"instance\":\"some-instance\"}})"]
```

without quotes:
```bash
✦2 at 17:24:39 ❯ jo -a $(jo labels=$(jo alertname="test-alert" service="test alert" severity="warning" routing_key="somestring" alert_type="node" node_name="none" namespace="nonexistent" annotations=$(jo summary="some summary") instance="some-instance"))
Argument `summary"}' is neither k=v nor k@v
```
```json
[{"labels":"{\"alertname\":\"test-alert\",\"service\":\"test"}]
```

It was the the last one that baffled me. **Why is the output getting truncated**? So I started troubleshooting

### Troubleshooting

This truncated output giving no intelligible errors:
```bash
✦2 at 17:07:38 ❯ jo -a $(jo status=firing labels=$(jo alertname="test-alert" service="test alert" severity="warning" routing_key="somestring" alert_type="node" node_name="none" namespace="nonexistent" cluster="a-alpha" instance="some-instance")) 
```
```json
[{"status":"firing","labels":"{\"alertname\":\"test-alert\",\"service\":\"test"}]
```

In troubleshooting, I started removing elemental objects to see if I could isolate a problematic area of my command and I finally I got to the following examples:

...this rendered correctly if I removed the space from the `service` property string:
```bash
✦2 at 16:53:56 ❯ jo -a $(jo labels=$(jo alertname="test-alert" service="test_alert"))
```
```json
[{"labels":{"alertname":"test-alert","service":"test_alert"}}]
```

That's good! But spaces should be allowed, and that's exactly what I'm actually trying to create. However:

...this renders a string (tried with and without wrapping with quotes. This shows without quotes):
```bash
✦2 at 16:54:19 ❯ jo -a $(jo labels=$(jo alertname="test-alert" service="test alert"))
Argument `alert"}' is neither k=v nor k@v
```
```json
[{"labels":"{\"alertname\":\"test-alert\",\"service\":\"test"}]
```

notice how jo yields the entire `labels` object as a string and the `service` property was truncated removing "` alert `" altogether.

...and for grins and giggles, I thought...maybe if I surround the inside `jo` with quotes?

```bash
✦2 at 17:01:41 ❯ jo -a $(jo labels="$(jo alertname="test-alert" service="test alert")")
```
```json
["{\"labels\":{\"alertname\":\"test-alert\",\"service\":\"test","alert\"}}"]
```

If I don't wrap the internal object with `jo -a` (to create the object as an array, which is what I need to do) then  I don't have this problem:

```bash
✦2 at 17:06:28 ❯ jo labels="$(jo alertname="test-alert" service="test alert")"
```
```json
{"labels":{"alertname":"test-alert","service":"test alert"}}
```

What could I be doing wrong here?

**Comment by gromgit** [comment]
You forgot to quote the outermost `jo` input:
```
$ jo -a "$(jo labels="$(jo alertname="test-alert" service="test alert")")"
[{"labels":{"alertname":"test-alert","service":"test alert"}}]
```
This is becoming an FAQ, because one variant or another of the following clause is arguably the best-kept secret in every shell, not just bash:
> The order of expansions is: brace expansion; tilde expansion, parameter and variable expansion, arithmetic expansion, and command substitution (done in a left-to-right fashion); word splitting; and pathname expansion.

In your example, the outermost input was command-substituted correctly, but then word splitting around the space in `test alert` meant `jo` saw _two_ elements to insert into an array.

**Comment by notjames** [comment]
> You forgot to quote the outermost `jo` input:
> 
> ```
> $ jo -a "$(jo labels="$(jo alertname="test-alert" service="test alert")")"
> [{"labels":{"alertname":"test-alert","service":"test alert"}}]
> ```
> 
> This is becoming an FAQ, because one variant or another of the following clause is arguably the best-kept secret in every shell, not just bash:
> 
> > The order of expansions is: brace expansion; tilde expansion, parameter and variable expansion, arithmetic expansion, and command substitution (done in a left-to-right fashion); word splitting; and pathname expansion.
> 
> In your example, the outermost input was command-substituted correctly, but then word splitting around the space in `test alert` meant `jo` saw _two_ elements to insert into an array.

geeez! Well, besides feeling a little lame, I sincerely appreciate your help in pointing out my mistake. Thank you!
