### ISSUE TITLE
Modifications to GPLv2 license make jo difficult to adopt in enterprise environment

### ISSUE THREAD

**Issue by rl-rantaj** [jpmens/jo#206]
The license for `jo`, https://github.com/jpmens/jo#License-1-ov-file, is not the GPLv2 license as-is, but an extended version with custom language. This means that for companies intending to use it, a separate legal review needs to be initiated to ensure that the license wording is fit for use, as the default rules for GPLv2 projects do not apply because of the possible modifications in the custom text. For a nice-to-have utility like `jo`, this review is often not worth starting, and thus the utility cannot be used.

**Comment by jpmens** [comment]
I read "enterprise" and "companies". I'm sure you'll be able to solve the issue.

**Comment by rl-rantaj** [comment]
Fair enough. There's no issue per se, just a blocker for adoption.
