### ISSUE TITLE
Please support empty array

### ISSUE THREAD

**Issue by lamyergeier** [jpmens/jo#207]
`jo` hangs up when the array is empty

```bash
$ Name=()
$ echo "${Name[@]}"

$ jo -a "${Name[@]}"
```

This is important as sometimes the Array is empty and I want jo to make empty array in json

**Comment by gromgit** [comment]
The problem you're running into is that expanding an empty array results in _no arguments at all_, so `jo` is waiting for a list of array elements from standard input.

A workaround:
```
$ jo -a "${Name[@]}" </dev/null
[]
```
This should always do the right thing, since `jo` only reads from stdin under very specific circumstances.
