### ISSUE TITLE
pass multiple variables to jo?

### ISSUE THREAD

**Issue by dynabler** [jpmens/jo#208]
I'm a non-developer and have read the manual, looked at code/tests for examples and countless other pages. I also kept using ShellCheck for errors. What is the best way to tackle my next challenge:

I have `raw.json` and use grep/awk/other to get 2 values. Uploads are calculated based on occurrence of a year. So 3x 2019 = 2019 3, 10x 2020 = 2020 10. What's the best way to use jo and the 2 values to get a json file?

```bash
#!/bin/bash
jo_bin=C:/jo/bin/jo.exe

file="raw.json"
uploads=$(grep -o -i '"year":[[:blank:]][[:digit:]]\{4\}' $file | grep -o '[[:digit:]]\{4\}' | sort -n | uniq -c | cat | awk '{print $1}')
year=$(grep -o -i '"year":[[:blank:]][[:digit:]]\{4\}' $file | grep -o '[[:digit:]]\{4\}' | sort -n | uniq -c | cat | awk '{print $2}')

$jo_bin -p
// I'm stuck here
```
Expected data.json

```json
[
    {
        "year": 2019,
        "uploads": 234
    },
    {
        "year": 2020,
        "uploads": 534
    }
// rest of json
]
```

I can use the above bash script and save the values to a text file. Maybe going this route is easier? Just mention it for sake of solutions.

```text
2010 12
2011 3
2012 14
2013 10
2014 2
```

Any direction/help is welcome.

**Comment by gromgit** [comment]
Extracting data from a JSON file with text tools like `grep` is generally not a good idea; one little change in the data and your script suddenly outputs nothing or (worse) incorrect values. Use a tool that understands JSON to tear `raw.json` apart, like [`jq`](https://jqlang.github.io/jq/).

That said, something like the following should work without introducing any new tools (UNTESTED):
```bash
# your original data gathering pipeline (minus the unnecessary `cat`)
grep -o -i '"year":[[:blank:]][[:digit:]]\{4\}' $file | grep -o '[[:digit:]]\{4\}' | sort -n | uniq -c |
# bash's builtin read is your friend
while read -r uploads year; do
  # generate each internal object
  jo year="$year" uploads="$uploads"
done | 
# shove them all into a JSON array
jo -p -a
```

**Comment by jpmens** [comment]
@dynabler contributions gladly accepted. :-)
