### ISSUE TITLE
jo extends fractional part of some floats

### ISSUE THREAD

**Issue by calebgross** [jpmens/jo#209]
When I provide a float as the value to a key, and that float is interpreted as a number, the fractional part gets weirdly extended. This only happens for some numbers. Here's a small sample showing floats between 0.0–10.0:

```
jo -v
jo 1.9

seq -f %.1f 0 .1 10 |
    xargs -I {} bash -c "echo -n '{} '; jo num={}" |
    grep -E '\.[0-9]{2,}'

8.2 {"num":8.199999999999999}
8.3 {"num":8.300000000000001}
8.7 {"num":8.699999999999999}
8.8 {"num":8.800000000000001}
9.2 {"num":9.199999999999999}
9.3 {"num":9.300000000000001}
9.7 {"num":9.699999999999999}
9.8 {"num":9.800000000000001}
```

There's a bit of an observable pattern—seems to happen when the fractional part leads with 2, 3, 7, or 8.

**Comment by jpmens** [comment]
That's the way numbers are emitted in the `json.c` functions we use https://github.com/jpmens/jo/blob/02be1303de6e6d9b9635cf8290f1637c754fc456/json.c#L1326

There's not much we can do to that other than introduce some special formatting option in `jo`, and I don't think we'll do that.

**Comment by calebgross** [comment]
Interesting. Well, it's not a huge issue—I can use `jo -- -s` to treat it as a string and then `jq tonumber` to change it back a number. Just unexpected behavior that took me a while to find the root cause 😅

```
seq -f %.1f 0 .1 10 |
    xargs -I {} jo -- -s num={} |
    jq -c '.num = (.num | tonumber)' |
    tail -n 15

{"num":8.6}
{"num":8.7}
{"num":8.8}
{"num":8.9}
{"num":9.0}
{"num":9.1}
{"num":9.2}
{"num":9.3}
{"num":9.4}
{"num":9.5}
{"num":9.6}
{"num":9.7}
{"num":9.8}
{"num":9.9}
{"num":10.0}
```
