### ISSUE TITLE
Problem with nested jo calls and a values with spaces in it

### ISSUE THREAD

**Issue by jjmurre** [jpmens/jo#211]
This input: `jo match=$(jo keyword="John Doe")`  gets met this ouput: `Argument Doe is neither k=v nor k@v`.

I tried without quotes, with single quotes an with escaped quotes. I think I am missing something trivial here.

**Comment by jpmens** [comment]
This is not a jo but a shell escaping issue.

**Comment by jpmens** [comment]
This is not a jo but a shell escaping issue.

```
$ jo -p match="$(jo keyword='John Doe')"
{
   "match": {
      "keyword": "John Doe"
   }
}
```

**Comment by jjmurre** [comment]
Allright, that was my hunch, but could not get around it. Thx. for the explantation and the way to solve it!
