### ISSUE TITLE
enhancement: `k=@file`

### ISSUE THREAD

**Issue by bibby** [jpmens/jo#22]
Great project, @jpmens .
An easily dismissable feature idea for you;

 As with [curl](https://curl.haxx.se/docs/manpage.html#-d) and [vault](https://www.vaultproject.io/docs/commands/read-write.html), it could be nice to serialize the contents of a file using the `@` prefix.

Example:

    $ jo -p authors=@AUTHORS
    {
       "authors": "Jan-Piet Mens <jpmens@gmail.com>"
    }

Currently I'm using `cat`, which is fine, honestly.

    $ jo -p authors="$(cat AUTHORS)"

**Comment by jpmens** [comment]
I'd thought of doing that (in spite of feature creep :-)
What I don't like about it is that it clashes with my (probably bad) choice of using `@` for indicating booleans: this makes my eyes water:

```
$ jo pass@T authors=@AUTHORS
```

Let's think about this a bit.

**Comment by itchyny** [comment]
We can already specify boolean with `=true` so dropping support for `@T` is easy to fix. The change breaks the backwards compatibility though.

**Comment by jpmens** [comment]
The proposed change doesn't break backward compatibility. Consider the difference:

```bash
$ jo bool@T
$ jo file=@AUTHORS
```

**Comment by itchyny** [comment]
Oh, yes. You are right. Sorry.

**Comment by jpmens** [comment]
@bibby I like this, and it's going to happen with a twist. Stay tuned. :smiley:

**Comment by bibby** [comment]
I look forward to it. `jo` has saved me quite a bit of time this week.

**Comment by bibby-nh** [comment]
just wanted to come back and necro a four year old ticket to say that I still love `jo`, and make use of it regularly. It's a great companion to `jq`, and has made many tasks so much easier these years. Much appreciated.

**Comment by jpmens** [comment]
That’s nice to hear, thanks.
