### ISSUE TITLE
Program name "jo" conflicts with AutoJump commands. Add "json" as an extra alias?

### ISSUE THREAD

**Issue by chuanconggao** [jpmens/jo#24]
[AutoJump](https://github.com/wting/autojump) uses `jo` to open a folder. This conflicts with JO's name here. I had to map `jo` to `json` to make it work. 

How about we add an extra alias `json` (which seems does not conflict with any existing tools)?

**Comment by gromgit** [comment]
@chuanconggao The [`json`](http://trentm.com/json/) command line program also exists, and its functionality looks to be orthogonal to `jo`, so there's an non-zero probability that someone would want the two on the same system.

In my opinion, aliases, script wrappers and other methods of localized renaming should remain the responsibility of end-users, and not be "enshrined" in the main source tree. Down that road lies madness, and a multi-way tug-of-war with @jpmens in the middle. :scream:

**Comment by jpmens** [comment]
JP will not stand in the middle, and he won't rename the program. @gromgit has said it all.

**Comment by albertobissacco** [comment]
so how can i use both?

**Comment by jpmens** [comment]
If it's installed in `/usr/local/bin` with the typical means: `/usr/local/bin/jo`.

**Comment by serdardalgic** [comment]
If you installed `jo` via brew, you can get both of them working by adding the following line to your shell rc, e.g. `~/.zshrc` if you are using zsh:
```
alias jsono="$(brew --prefix jo)/bin/jo"
```
