### ISSUE TITLE
jo hangs on arrays with failed, unquoted subcommands

### ISSUE THREAD

**Issue by jsocol** [jpmens/jo#3]
If a subcommand fails (e.g. from the `s/jo/joe` typo below), `jo` handles it fine in the case of assigning object values (sets to `null`) but not in some cases with `-a`, e.g.:

```shell
# works fine
$ jo foo=$(joe bar=1)
bash: joe: command not found
{"foo":null}

# quoted, works fine with -a
$ jo -a "$(cat LICENSE2)"
cat: LICENSE2: No such file or directory
[null]

# also works fine with -a
$ jo -a "$(cat2 LICENSE)"
bash: cat2: command not found
[null]

# hangs on unquoted subcommands
$ jo -a $(joe a@t)
bash: joe: command not found

# but doesn't hang on unquoted subcommands with objects
$ jo foo=$(joe a@t)
bash: joe: command not found
{"foo": null}
```

The difference with and without the `-a` flag is interesting. But if it's a bash quirk and there's nothing else to do, maybe updating the examples to use quoted subcommands would help?

**Comment by jpmens** [comment]
Other than confusing the heck out of me with your use of joe (which I have here so it produces quite "interesting" effects): The reason it appears to "hang" is because the bash expansion is empty, hence `jo` is trying to read _stdin_. Works as expected.

**Comment by jpmens** [comment]
So, your last and second to last examples basically translate to:

```
$ jo -a

$ jo foo=
```

The first is now reading _stdin_. The latter has an empty value and therefore produces `null`.

**Comment by jsocol** [comment]
:+1: thanks for clarifying!
