### ISSUE TITLE
Can't nest objects in an array.

### ISSUE THREAD

**Issue by ffernand** [jpmens/jo#35]
Nesting objects in an array doesn't appear to work.

Example...
`$ jo -p devices[]="$(jo device=android version=1.2.3)" devices[]="$(jo device=ios version=4.5.6)"`

```
{
  "devices":[]
}
```

I would have expected the following...

```
{
  "devices": [
    {
      "device": "android", 
      "version": "1.2.3"
    }, 
    {
      "device": "ios", 
      "version": "4.5.6"
    }
  ]
}
```

PS: The tool is great BTW... thanks very much for releasing it!!!

**Comment by jpmens** [comment]
That syntax is indeed _suboptimally implemented_, and I've marked as a bug.

Workaround:

```
$ jo -p devices=$(jo -a "$(jo device=android version=1.2.3)" "$(jo device=ios version=4.5.6)")
{
   "devices": [
      {
         "device": "android",
         "version": "1.2.3"
      },
      {
         "device": "ios",
         "version": "4.5.6"
      }
   ]
}
```

**Comment by jpmens** [comment]
Related: #27 and #28

**Comment by jpmens** [comment]
Example works, so closing.
