### ISSUE TITLE
Building on SmartOS (and presumably other Solarish) fails

### ISSUE THREAD

**Issue by bdha** [jpmens/jo#37]
From `jo-1.0`:

```
# make
  CC       jo.o
  CC       json.o
json.c:134:18: error: conflicting types for 'uchar_t'
In file included from /usr/include/sys/wait.h:37:0,
                 from /usr/include/stdlib.h:41,
                 from json.c:29:
/usr/include/sys/types.h:100:23: note: previous declaration of 'uchar_t' was here
Makefile:562: recipe for target 'json.o' failed
make: *** [json.o] Error 1
```

Happy to provide resources for testing / building. (Commenting out `json.c:134` "fixes" it, though I imagine that isn't the intention. I don't speak much C, sorry!)

**Comment by jpmens** [comment]
@bdha thanks for your report. Could you grab the `json.c` I've just modified and replace the one you have with it, then `make clean` and `make`? I hope that solves the issue.

**Comment by mamash** [comment]
This is the same issue as sass/libsass#1099 btw.

**Comment by jpmens** [comment]
Closing for lack of response

**Comment by mamash** [comment]
Just to confirm, as of 1.1, jo builds fine and with no patches needed on SmartOS/SuOS.
