### ISSUE TITLE
jo hanging on for what ? 

### ISSUE THREAD

**Issue by jjvein** [jpmens/jo#38]
When I just typed the command `jo` without any parameters in my terminal, it just hang on .  

Then I tried to input  `name=jjvein`, ok, no stdout, then `name`, stderror just like 'Argument `name' is neither k=v nor k@v'.

How can i use this way to create my JSON?

**Comment by itchyny** [comment]
Input `foo=bar` and press `<C-d>`, the common way to end the stdin by sending SIGINT. But this behaviour can be improved. For example, jq without argument prints the help.

**Comment by jjvein** [comment]
yes, i once tried to end it by typing `exit`, `quit`, e.g....
haha, but forgot to use <C-d> to terminate it.
Thanks a lot.

**Comment by jpmens** [comment]
What you probably want is

```
$ jo name=jvein
{"name":"jvein"}
$
```
