### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [jpmens/jo#39]
Would you like to add more error handling for return values from functions like the following?
- [ftello](http://pubs.opengroup.org/onlinepubs/9699919799/functions/ftello.html) ⇒ [slurp_file](https://github.com/jpmens/jo/blob/28de33ebf161f4edc24de63da0269027274a32a7/jo.c#L82)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [main](https://github.com/jpmens/jo/blob/28de33ebf161f4edc24de63da0269027274a32a7/jo.c#L430)

**Comment by jpmens** [comment]
Error handling on a `printf()`? Sure, go ahead -- I'd take a pull-request. ;-)
