### ISSUE TITLE
Why three space indentation  ?

### ISSUE THREAD

**Issue by who** [jpmens/jo#40]
Looks like `jo` uses three spaces for indentation.

```
$ echo -e '{"a":"b"}\n{"c":"d"}' | jo -pa
[
   {
      "a": "b"
   },
   {
      "c": "d"
   }
]

```

Could this be changed to 2 by default, or perhaps made an option ?

**Comment by jpmens** [comment]
This [has been discussed](https://github.com/jpmens/jo/pull/18); the answer is basically "it doesn't matter; they all do it differently anyway".

**Comment by who** [comment]
Fair enough, people do it differently, which is why it may be nice for making it an option. For now I'll just use `jq` for pretty printing as a workaround.

Like so: 

```
$ echo -e '{"a":"b"}\n{"c":"d"}' | jo -a | jq '.'
[
  {
    "a": "b"
  },
  {
    "c": "d"
  }
]
```
