### ISSUE TITLE
Escaped double quotes don't work

### ISSUE THREAD

**Issue by nikolay** [jpmens/jo#41]
`Value="\"loaderio=${record_value}\""` doesn't work as expected as only works as the unintuitive `Value=\"\"loaderio=${record_value}\"\"`, which can easily break if there are spaces within `${record_value}`, I guess. It would break if the variable contains double quotes as well.

**Comment by gromgit** [comment]
Is this what you actually wanted?
```sh
$ record_value="123 456 \"coming down the mountain\""
$ echo $record_value
123 456 "coming down the mountain"
$ jo value=\"loaderio="${record_value}"\"
{"value":"loaderio=123 456 \"coming down the mountain\""}
```
If not, what is the output you expected, given the above value of `$record_value`?

**Comment by nikolay** [comment]
@gromgit This is what works (but depends on the value of `record_value`):
```
$ record_value="test"
$ jo value=\"\"loaderio=${record_value}\"\"
{"value":"\"loaderio=test\""}
$ record_value="123 456 \"coming down the mountain\""
$ jo value=\"\"loaderio=${record_value}\"\"
Argument `456' is neither k=v nor k@v
Argument `"coming' is neither k=v nor k@v
Argument `down' is neither k=v nor k@v
Argument `the' is neither k=v nor k@v
Argument `mountain"""' is neither k=v nor k@v
{"value":"\"loaderio=123"}
```
As you can see, this is unreliable.

What I expected to work was this:
```
$ record_value="123 456 \"coming down the mountain\""
$ jo value="\"loaderio=${record_value}\""
{"value":"loaderio=123 456 \"coming down the mountain\""}
```
but it doesn't as you can see.

**Comment by gromgit** [comment]
If I understand you correctly, what you actually want is an object with property `value` whose value is literally `loaderio=\"123 456 \\\"coming down the mountain\\\"`, i.e. a JavaScript assignment expression in which `loaderio` is given the value `123 456 "coming down the mountain"`:
```js
a={"value": "loaderio=\"123 456 \\\"coming down the mountain\\\"\""}
a.value   // => 'loaderio="123 456 \"coming down the mountain\""'
loaderio  // => Uncaught ReferenceError: loaderio is not defined
eval(a.value)
loaderio  // => '123 456 "coming down the mountain"'
```

If so, the issue you're running into isn't with `jo`, but with your shell, specifically with the interaction between variable expansion and word splitting, with quoting rules thrown in for good measure. This may vary from shell to shell, so I'll just illustrate a solution for Bourne-style shells:
```sh
$ record_value="123 456 \\\"coming down the mountain\\\""
$ jo value="\"loaderio=\"${record_value}\"\""
{"value":"loaderio=\"123 456 \\\"coming down the mountain\\\"\""}
```

**Comment by nikolay** [comment]
@gromgit No, the as TXT DNS record, the whole `loaderio=...` as a value should be in escaped double-quotes, i.e. `"loaderio=..."`.

The issue is that jo does this poorly - just to entertain the edge case where you want a number or a boolean as a string, I removes the escaped quotes! Instead, why doesn't it just implement a positional flag, for example:

```
$ jo -s a=true b=true -s c=123 d=123
{"a":"true","b":true,"c":"123","d":123}
```

In fact, the ugly booleans can be done more elegantly using a similar type guiding:
```
$ a=1
$ jo -b a="$a" -b b="true" -b c=0 -b d
{"a":true,"b":true,"c":false,"d":true}
```

**Comment by nikolay** [comment]
@jpmens Any comment?

**Comment by jpmens** [comment]
Yes: my head spins when I see the above quote orgy. ;-)

If you provide or somebody else provides a pull-request to do this properly, I'd probably take it.

**Comment by nikolay** [comment]
@jpmens Okay, I will give it a try.

**Comment by jpmens** [comment]
@gromgit that looks excellent; make it happen!
