### ISSUE TITLE
No match in FreeBSD using csh

### ISSUE THREAD

**Issue by lucamolteni** [jpmens/jo#44]
I'm using this port https://www.freshports.org/textproc/jo/
```
~ % echo $0
-csh
~ % jo -p number=17 pass=true geo[lon]=88 geo[cc]=ES point[]=1 point[]=2 geo[lat]=123.45
jo: No match.
~ % 

```

**Comment by kirbyfan64** [comment]
Does it work with others shells? You might just need to put quotes around each arguments.

**Comment by gromgit** [comment]
@kirbyfan64 is right, you need to quote all arguments that contain `[ ]`, otherwise `csh` will try to do filename expansion on them, and abort noisily when it fails. (Yes, that's `csh` saying `No match`, not `jo`.)

```sh
% jo -p number=17 pass=true "geo[lon]=88" "geo[cc]=RS" "point[]=1" "point[]=2" "geo[lat]=123.45"
{
   "number": 17,
   "pass": true,
   "geo": {
      "lon": 88,
      "cc": "RS",
      "lat": 123.45
   },
   "point": [
      1,
      2
   ]
}
```
