### ISSUE TITLE
Memory access error - core dump

### ISSUE THREAD

**Issue by hevilp** [jpmens/jo#45]
error message

`geonom@ubuntu-nominatim:~$ ./y
./y: Zeile 21: 17748 Speicherzugriffsfehler  (Speicherabzug geschrieben) jo type=FeatureCollection`

dmesg:
`[16001.116809] jo[19910]: segfault at 0 ip 0000000000401a7b sp 00007ffe30358930 error 6 in jo[400000+6000]
`

the code
https://gist.github.com/hevilp/b267e763f33e70fb7e0b5575b459fec9

**Comment by jpmens** [comment]
I'm not sure how you expect people to help you ... You have not provided the data that results in the core dump, and please provide the shortest possible invocation of `jo` which causes this, in other words, omit all that is not necessary and paste that here within a code block.

**Comment by hevilp** [comment]
Sorry, but where can I find the core dump of jo? I am running 16.04. Ubuntu.

**Comment by hevilp** [comment]
Here is the easiest possible code:
https://gist.github.com/hevilp/b267e763f33e70fb7e0b5575b459fec9

**Comment by gromgit** [comment]
@hevilp First, rebuild the latest release version of `jo`. I've never had `jo` segfault on me, so there's something weird with your binary.

Also, there are a couple of issues with the script you posted:

1. `echo The counter is $COUNTER` pollutes the JSON you're returning to the outer `jo` invocation. You probably want to redirect that to stderr, i.e. `echo The counter is $COUNTER >&2`
1. `LON=$LON+1` actually turns `LON=100` into `LON=100+1`, which probably isn't what you want. Do `let LON=LON+1` instead.

That said, `jo` has a known problem (bug #35) building arrays of objects. To work around this, you need to build the `features` array as a separate step, then integrate the results into your primary object.

Based on all the above, your script now looks like this:
```sh
#!/bin/bash
{
  COUNTER=0
  LON=100
  LAT=200
  FEATURES=()

  while [  $COUNTER -lt 10 ]; do
    echo The counter is $COUNTER >&2
    let COUNTER=COUNTER+1
    FEATURES+=("$(jo type=Feature geometry="$(jo type=Point coordinates[]=$LON coordinates[]=$LAT)" properties="$(jo name="Test")")")
    let LON=LON+1
    let LAT=LAT+1
  done
  jo type=FeatureCollection features="$(jo -a "${FEATURES[@]}")"
} > 01test.txt
```

**Comment by jpmens** [comment]
@gromgit thank you for taking the time to dig into this; much appreciated.
