### ISSUE TITLE
store strings which has spaces in between

### ISSUE THREAD

**Issue by AshStuff** [jpmens/jo#48]
i tried assigning variable which has space in between them to json using jo .. Its not accepting.

Lms="build0 build1 build2"
jo LMs=$Lms

Error:
Argument `build1' is neither k=v nor k@v
Argument `build2' is neither k=v nor k@v
{"lms":"build0"}

**Comment by jpmens** [comment]
Consider you're doing this in a shell which has first stab at your input.
Use double quotes around "$Lms"

**Comment by notjames** [comment]
double-quotes don't work either...:

```
$ jo -p t=$(jo some_key=$(jo -a $(jo foo=$(jo bar=\"baz qux\"))))
Argument `qux"' is neither k=v nor k@v
{
   "t": {
      "some_key": [
         {
            "foo": {
               "bar": "baz"
            }
         }
      ]
   }
}


$ jo -p t=$(jo some_key=$(jo -a $(jo foo=$(jo bar="baz qux"))))
Argument `qux"}' is neither k=v nor k@v
{
   "t": {
      "some_key": [
         {
            "foo": "{\"bar\":\"baz"
         }
      ]
   }
}
```

This is how it's working with `1.0`. I'm checking to make sure this is the latest version.

**Comment by tomryanx** [comment]
$ jo -p "t=$(jo "some_key=$(jo -a "$(jo "foo=$(jo bar="baz qux")")")")"
    {
       "t": {
          "some_key": [
             {
                "foo": {
                   "bar": "baz qux"
                }
             }
          ]
       }
    }
