### ISSUE TITLE
How to create an array of objects?

### ISSUE THREAD

**Issue by Sohaib12** [jpmens/jo#49]
I want an output that looks something like this:

`
  "targets": [{

        "name" : "somename",
        "path" : "targets/somefile",
        "center" : {
            "x" : 41.821,
            "y" : 12.372,
            "z" : 0.942
        },
        "radius" : 10.0
    },
    {
        "name" : "somename",
        "path" : "targets/somefile",
        "center" : {
            "x" : 41.821,
            "y" : 12.372,
            "z" : 0.942
        },
        "radius" : 10.0
    }],`

Notice that it has an array of objects called "targets". But I can't seem to solve it.

**Comment by gromgit** [comment]
The [man page](https://github.com/jpmens/jo/blob/master/jo.md) states, in part:

> _jo_ creates an array instead of an object when `-a` is specified.

If you're having problems figuring out how to chain together multiple `jo` invocations to produce a complex object, remember that it's generally a simple mapping from the English description of the object. 

So, as you described it:

> an array...

```
jo -a ...
```

> ...of objects...

```
jo -a $(jo k1=v1) $(jo k2=v2)
```

> ...called `targets`

```
jo targets=$(
  jo -a $(jo k1=v1) $(jo k2=v2)
)
```
