### ISSUE TITLE
json parsing seems broken for strings containing spaces

### ISSUE THREAD

**Issue by PaulSmecker** [jpmens/jo#51]
`jo a=$(jo b="c d")`

expected:
`{"a":{"b":"c d"}}`

what i got:
```
Argument `d"}' is neither k=v nor k@v
{"a":"{\"b\":\"c"}
```

**Comment by kirbyfan64** [comment]
I think you need to enclose both parts with quotes:

```
jo "a=$(jo b="c d")"
```

**Comment by jpmens** [comment]
Response by @kirbyfan64 is correct: this is not a `jo` issue, rather a shell-escaping problem:

```
jo "a=$(jo b="c d")"
{"a":{"b":"c d"}}
```
