### ISSUE TITLE
Support find-like nesting

### ISSUE THREAD

**Issue by scallopedllama** [jpmens/jo#52]
I think it would be neat to do be able to do nesting with `jo` without having to use sub-calls to the program. I think that this would be implemented in an intuitive way by copying how find does it.

Take the example from the manual:
```
jo -p name=JP object=$(jo fruit=Orange hungry@0 point=$(jo x=10 y=20 list=$(jo -a 1 2 3 4 5)) number=17) sunday@0
```

Could potentially work like this instead with only one call to `jo`:

```
jo -p name=JP object= \( fruit=Orange hungry@0 point= \( x=10 y=20 list= \( -a 1 2 3 4 5 \) \) number=17 \) sunday@0
```

This could potentially allow for more advanced usage of `jo` using xargs than is currently possible though I acknowledge that it could make syntax a bit harder to parse.

**Comment by jpmens** [comment]
IMO too complicated. Be that as it may I won't implement this, but contributions might be accepted.
