### ISSUE TITLE
Assertion `utf8_validate(str)' failed

### ISSUE THREAD

**Issue by rwhitworth** [jpmens/jo#53]
Hello,
I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the `jo` program on Linux. Is fixing the crashes/aborts from these input files something you're interested in? The input files can be found here: https://github.com/rwhitworth/jo-fuzz.

The files can be executed as `./jo -p < id_filename` to cause the issue.

Let me know if I can provide any more information to help narrow down this issue.

**Comment by rwhitworth** [comment]
Example crash/abort:
```
# valgrind ./jo -p < ../jo-fuzz/2017-05-16/id\:000000\,sig\:06\,src\:000000\,op\:havoc\,rep\:128
==15504== Memcheck, a memory error detector
==15504== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==15504== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==15504== Command: ./jo -p
==15504==
jo: json.c:1117: void emit_string(SB *, const char *): Assertion `utf8_validate(str)' failed.
==15504==
==15504== HEAP SUMMARY:
==15504==     in use at exit: 190 bytes in 5 blocks
==15504==   total heap usage: 7 allocs, 2 frees, 385 bytes allocated
==15504==
==15504== LEAK SUMMARY:
==15504==    definitely lost: 0 bytes in 0 blocks
==15504==    indirectly lost: 0 bytes in 0 blocks
==15504==      possibly lost: 0 bytes in 0 blocks
==15504==    still reachable: 190 bytes in 5 blocks
==15504==         suppressed: 0 bytes in 0 blocks
==15504== Rerun with --leak-check=full to see details of leaked memory
==15504==
==15504== For counts of detected and suppressed errors, rerun with: -v
==15504== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Aborted
```

**Comment by jpmens** [comment]
Thank you for the data and the issue. Well, partial thank you, of course. :-)
The example you just posted, crashes in `emit_string()` which is part of `json.[ch]` by Joseph A. Adams. What I'm going to attempt first is to see if he still exists and is willing to investige his own code.

Unless, of course, you feel up to fixing the bugs?

**Comment by jpmens** [comment]
If my google-fu isn't completely off, @joeyadams is the author of `json.[ch]`. I've also sent him an email asking whether he'd be willing to come by and give me a hand. :-)

**Comment by rwhitworth** [comment]
> Unless, of course, you feel up to fixing the bugs?

I browsed the source a bit, but I'm far from an expert.  Is an assertion the correct way to handle this input type?  Seems like emit_string should have a return type set (non-void) and let the calling function know an error occurred, and let that error pass up to an appropriate function that lets the user know about the problem.

I'll let you or Joey make the call as you're both much more familiar with the code base (and the C language) than I am.

**Comment by joeyadams** [comment]
I did indeed write `json.[ch]`.  Technically, this assert is catching an error in usage, as all strings in the `JsonNode` tree are required to be UTF-8.  I made this library strict about Unicode because JSON supports Unicode escapes, and mixing such escapes with non-Unicode text can lead to text that isn't representable in any encoding.

But you can take out the first two asserts in emit_string, and it will invoke fallback code that replaces invalid codes with U+FFFD.  You could also modify emit_string to emit non-ASCII characters as-is (but retain the escaping logic for control characters), but that would prevent encoding mistakes from being caught early.

If you want to fix this by reporting an error when invalid UTF-8 is detected, you can add validation to the code that parses input, so the user will know what argument is invalid.  You could also call `json_check` prior to `json_encode`, to search the `JsonNode` tree for invalid strings.

**Comment by jpmens** [comment]
@rwhitworth after the aforementioned `assert()` removal, I'm now able to run

```bash
find fuzz/jo-fuzz/2017-05-16/ -type f | while read f; do ./jo < "$f"; done
```

without jo crashing. Could you verify again please?

**Comment by rwhitworth** [comment]
I'm not sure this was a net positive change.  Examples:
```
jo: json.c:591: void json_append_member(JsonNode *, const char *, JsonNode *): Assertion `object->tag == JSON_OBJECT' failed.
```
and
```
jo: json.c:575: void json_append_element(JsonNode *, JsonNode *): Assertion `array->tag == JSON_ARRAY' failed.
```

Input files available here: https://github.com/rwhitworth/jo-fuzz/tree/master/2017-05-22

**Comment by jpmens** [comment]
I'm not sure what the point of this excercise is going to be; it's not as though jo would typically get fuzzed binary data fed to it by users in a shell... (Of course any program should be as solid as possible, but I'm thinking this is stretching things a bit. ;)

If somebody wants to take on the task, I'll take a PR.

**Comment by rwhitworth** [comment]
I understand if this falls outside the expected use case for jo.  I won't be able to provide a PR and I also understand if you would rather revert the change made and close this issue.

**Comment by gromgit** [comment]
I'd personally err on the side of safety, and keep Joey Adams' original asserts.
As a data-transformation tool, I don't think it's a good idea for `jo` and/or Joey's code to quietly change the user's input...and generate stuff that the user wasn't expecting. Better for `jo` to WTF loudly and unmistakably.
