### ISSUE TITLE
Can't avoid object nesting

### ISSUE THREAD

**Issue by eliaslevy** [jpmens/jo#58]
It appears there is no way to embed JSON as a string field within a JSON object.  E.g. both `jo k1=$(jo k2=v)` and `jo -- -s k1=$(jo k2=v)` generate `{"k1":{"k2":"v"}}`.  I would expect the later to generate `{"k1":"{\"k2\":\"v\"}"}` via coercion.

Is there a way to generate the later?

**Comment by gromgit** [comment]
Sure. You just need to make the value assigned to `k1` look like a string, by quoting it properly:
```
$ jo k1=\"$(jo k2=v)\"
{"k1":"\"{\"k2\":\"v\"}\""}
```
> I would expect the later to generate `{"k1":"{\"k2\":\"v\"}"}` via coercion.
The coercion patch I wrote is only intended to override the guessing of _base_ types (number, string, boolean).

**Comment by eliaslevy** [comment]
The output is wrong.  Look the k1 value string.  It should be `"{\"k2\":\"v\"}"` instead it is `"\"{\"k2\":\"v\"}\""`

**Comment by jpmens** [comment]
I am not interested in making this possible. If somebody wants to do it, I'll accept a patch.

**Comment by madskaddie** [comment]
https://github.com/jpmens/jo/pull/99

**Comment by jpmens** [comment]
implemented in #99
