### ISSUE TITLE
Quoted numbers (read strings) are auto-converted to numbers

### ISSUE THREAD

**Issue by nickzam** [jpmens/jo#6]
This is ok:
=> jo a=1
<= {"a":1}

This is wrong:
=> jo a="1"
<= {"a":1}
=> jo a='1'
<= {"a":1}

This is bad:
=> jo a='1.0'
<= {"a":1}
=> jo a="1.0"
<= {"a":1}

I would expect passing value to json "as it is" if it's quoted, doesn't matter if it is integer or float.

**Comment by jpmens** [comment]
In your 2nd example there's not much I can do: the quotes _belong_ to the shell and it strips them off before _jo_ sees them.

I don't really know how to solve the behavior in your 3rd example other than introducing a _force to string_ option which would avoid the numeric conversion we now do. Would that be acceptable do you think?

Something along the lines of 

```bash
$ jo -N a=1.0
{"a":"1.0"}

$ jo -N b=2
{"b":"2"}
```

**Comment by nickzam** [comment]
What about using \ to shield the quotes? 
Now, it doesn't work:
=> jo a=\"1.0\"
<= {"a":"\"1.0\""}

I should be: 
=> jo a=\"1.0\"
<= {"a":"1.0"}

**Comment by jpmens** [comment]
That's the way I've done it; thank you for your feedback!

**Comment by nickzam** [comment]
Thank you, patch works for me. Good job!
