### ISSUE TITLE
Quoting number to make them strings doesn't work in 1.1

### ISSUE THREAD

**Issue by skowpio** [jpmens/jo#61]
```
$ jo a=\"1.0\"
{"a":"\"1.0\""}
$ jo -v
jo 1.1

$ jo a=\"1.0\"
{"a":"1.0"}
$ jo -v
jo 1.0

```
In 1.1 it should be the same as in 1.0 and as was described in Readme. I would like to have a string: 
1.0 not "1.0"

**Comment by gromgit** [comment]
I contributed a "type coercion" facility that was incorporated in v1.1, specifically to handle cases like yours without the pain of excessive quoting:
```
$ jo -- -s a=1.0
{"a":"1.0"}
```
See the man page for details.

**Comment by JeffCleverley** [comment]
Type coercion isn't working for me for numbers stored in variable

apiJson=$(jo -- source=$source server_ip=$serverIP status=success -s step=1 output="$output")

Outputting

{"source":"an-example.com","server_ip":"xxx.xxx.xxx.xxx","status":"success","step":1,"output":"staging.an-example.com successfully backed up...\\n"}

**Comment by jpmens** [comment]
Works fine in current version as far as I can tell:

```bash
$ jo step=1  # will be numeric
{"step":1}

$ jo -- -s step=1   # will be string
{"step":"1"}
```
