### ISSUE TITLE
can't use Space in value ?

### ISSUE THREAD

**Issue by BH1SCW** [jpmens/jo#62]
This project is very useful for me. Thanks you guys!
Here is 3 test case,  the second one is a bug ?  I can use space in string?

 jo -p real=$(jo monitor_procs='a')                                                                                                                                                         
{
   "real": {
      "monitor_procs": "a"
   }
}
 jo -p real=$(jo monitor_procs='a b')                                                                                                                                                       
Argument `b"}' is neither k=v nor k@v
{
   "real": "{\"monitor_procs\":\"a"
}
 jo -p real=$(jo monitor_procs="a,b")                                                                                                                                                       
{
   "real": {
      "monitor_procs": "a,b"
   }
}

**Comment by jpmens** [comment]
This is, as most cases are, also a shell quoting issue; not a _jo_ issue. Do this:

```
jo -p real="$(jo monitor_procs='a b')"
```

**Comment by BH1SCW** [comment]
Great Thank!
