### ISSUE TITLE
Cannot create array of large json objects

### ISSUE THREAD

**Issue by baldisbk** [jpmens/jo#63]
I was trying to create JSON array of several large JSON objects. I put them in files since they are too large for a command line.
When I tried to use jo like that:
`jo -a @file1 @file2`
I recognized that files' contents is interpreted as strings, not objects.

I also tried to pass contents of those files as input stream, but there was another problem. Every object must present as a single line in input, but length of input string seems to be limited by BUFSIZ bytes (8192 for me); longer strings are split into several strings that either produce error messages like "missing closing bracket on ..." or are interpreted as strings (not objects).

**Comment by jpmens** [comment]
Have you tried something along these lines:

```
$ cat /tmp/o
[
   { "name" : "Jane", "number" : 42 },
   { "name" : "John", "number" : 98 }
]

$ jo -p objects:=/tmp/o
{
   "objects": [
      {
         "name": "Jane",
         "number": 42
      },
      {
         "name": "John",
         "number": 98
      }
   ]
}
```

**Comment by baldisbk** [comment]
Yes, but it is not result I'm looking for. What I need is an array of object, like contents of /tmp/o in your example, but not an object with array. I cannot use ":=" with **-a**, can I?

**Comment by jpmens** [comment]
No, that's not possible.

**Comment by raksja** [comment]
Good to know that its not supported, as the huge dataset that i am trying to construct is "array of objects". 
`
[
{
   "name": "JP",
   "object": {
      "fruit": "Orange",
      "hungry": false
   },
   "sunday": false
},
{
   "name": "JP",
   "object": {
      "fruit": "apple",
      "hungry": false
   },
   "sunday": true
}
]
`
Is there any workaround at all?

**Comment by gromgit** [comment]
> Is there any workaround at all to achieve the above?

@raksja You'd have to use a proper JSON processor like [jq](https://stedolan.github.io/jq/), which for your purposes (appending large objects into a single array) is as easy as:
```
$ jq '[.]' large1.json large2.json large3.json ... largeN.json > array_of_large.json
```
The magic incantation `[.]` simply means "construct an array (`[]`) over each input as-is (`.`)".

**Comment by doronbehar** [comment]
I too feel this feature is missing out of the box. `jjo` seems to support that: https://github.com/memoryhole/jjo#create-array
