### ISSUE TITLE
Empty array?

### ISSUE THREAD

**Issue by tynes** [jpmens/jo#64]
Is it possible to create an empty array? I have tried:

`echo | jo -a` which produces `[null]`

**Comment by colindean** [comment]
`jo -p asdf=[]`

```json
{
   "asdf": []
}
```

but I think you might be trying to produce an output of simply

```json
[]
```

Unreleased commit 3566ed56d86cffd05c7b0076578b2fd53ccf3f05 adds -e option that makes jo not fail when it receives no input on STDIN, but the result is simply exiting 0.

**Comment by gromgit** [comment]
@tynes There are at least two ways to get what you want. The most obvious way is to simply `echo '[]'`, if you already know that you want an empty array.

The second relies on the fact that `jo` will always read from stdin if there are no non-option arguments available. Simply redirect `/dev/null` to jo's stdin, and it'll dutifully generate the appropriate empty object or array:
```
$ jo </dev/null
{}

$ jo -a </dev/null
[]
```
This is especially useful if you have a bash array that may be empty:
```
$ EMPTY_ARRAY=()
$ jo -a "${EMPTY_ARRAY[@]}" </dev/null
[]
```
