### ISSUE TITLE
Delimiter is ignored when reading JSON from file

### ISSUE THREAD

**Issue by vmmello** [jpmens/jo#65]
Trying the following test case with jo 1.1 from master branch:
`$ jo -p -d . parent.1st_obj.one=1 parent.1st_obj.two=2 parent.2nd_obj:=/tmp/2nd_obj.txt`

With the contents of `/tmp/2nd_obj.txt` being:
```
{"three":3, "four": 4}
```

The output returned is:
`$ jo -p -d . parent.1st_obj.one=1 parent.1st_obj.two=2 parent.2nd_obj:=/tmp/2nd_obj.txt`
```
{
   "parent": {
      "1st_obj": {
         "one": 1,
         "two": 2
      }
   },
   "parent.2nd_obj": {
      "three": 3,
      "four": 4
   }
}
```

Though I expected the following:
```
{
   "parent": {
      "1st_obj": {
         "one": 1,
         "two": 2
      },
      "2nd_obj": {
         "three": 3,
         "four": 4
      } 
   }
}
```

Is this a bug? Or I'm using it wrong?

**Comment by jpmens** [comment]
Looks like a bug to me.
