### ISSUE TITLE
useage

### ISSUE THREAD

**Issue by hemna** [jpmens/jo#68]
I didn't know where else to post a question like this, but I'm trying to use jo to convert the output of
lsb_release -a to a json dict.

lsb_release -a outputs lines delimited by a : and whitespace.   

```LSB Version:	n/a
Distributor ID:	openSUSE project
Description:	openSUSE Leap 42.3
Release:	42.3
Codename:	n/a

lsb_release -a | jo -p -a 
[
   "LSB Version:\tn/a",
   "Distributor ID:\topenSUSE project",
   "Description:\topenSUSE Leap 42.3",
   "Release:\t42.3",
   "Codename:\tn/a"
]

**Comment by hemna** [comment]
$ lsb_release -a | sed 's/\:\t/=/' | jo -p -a
```
[
   "Distributor ID=Ubuntu",
   "Description=Ubuntu 17.10",
   "Release=17.10",
   "Codename=artful"
]

**Comment by hemna** [comment]
"This is jo, a small utility to create JSON objects" from the command line.

**Comment by hemna** [comment]
Thanks for the useless comments and clear lack of actual support of your project for things other than your limited world view.  

smh.

**Comment by criztovyl** [comment]
@hemna
Your use case simple does not seem to be in scope of `jo`.

What you want to do is to transform a text stream to JSON.

What `jo` does is allowing you to conveniently(?) "manually" create JSON on the command line.

i.e. the following is what `jo` is made for.

    $ jo foo=bar trulla="$(jo blah=blubb)"
    {
         "foo": "bar",
         [...]
    }
