### ISSUE TITLE
Make Ubuntu Bionic PPA release

### ISSUE THREAD

**Issue by fastfrwrd** [jpmens/jo#79]
I'm attempting to move onto Bionic for a project, and I'm finding that when I attempt to `apt-get jo` from PPA, there isn't a version published for Bionic:

```
E: The repository 'http://ppa.launchpad.net/duggan/jo/ubuntu bionic Release' does not have a Release file.
```

**Comment by fastfrwrd** [comment]
i'm betting part of the solution is gonna require changing this file: https://github.com/jpmens/jo/blob/3566ed56d86cffd05c7b0076578b2fd53ccf3f05/debian/changelog#L1

@duggan do you have any insight on this? You seem to be the person who originally contributed that part

**Comment by duggan** [comment]
Hey @fastfrwrd; [jo was added to upstream a while back](https://packages.ubuntu.com/bionic/jo); using the PPA is no longer required.

Remove the entry from `/etc/apt/sources.d` and you should be good to go!

**Comment by jpmens** [comment]
Thank you, @duggan; closing as solved.

**Comment by fastfrwrd** [comment]
thank you!

**Comment by MatheusRV** [comment]
I'm running this with docker, implement a release file is better than remove from /etc/apt on dockerfile.

**Comment by MatheusRV** [comment]
Create a .deb or .rem maybe is a good ideia.
