### ISSUE TITLE
How to output an empty string

### ISSUE THREAD

**Issue by chriswhite199** [jpmens/jo#80]
Is it possible to output a field value as an empty string?

`jo a=""` outputs null as the field value and `jo a="''"` or `jo a='""'` both output the values a quoted empty strings:

```
jo -p a= b="" c='""' d="''"
{
   "a": null,
   "b": null,
   "c": "\"\"",
   "d": "''"
}
```

**Comment by jpmens** [comment]
```
jo -p -- -s a=""
{
   "a": ""
}
```
