### ISSUE TITLE
Asciinema is dead

### ISSUE THREAD

**Issue by maelvalais** [jpmens/jo#83]
Hi,

First off, I want to thank you so much. Using `jo` is a pleasure to use! 😁

I think the asciinema in the README leads to a dead screencast; it says:

> This recording has been archived
> 
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

Anyway, your tool is awesome!

**Comment by jpmens** [comment]
Thank you for reporting that and for your kind words
