### ISSUE TITLE
Argument `20:03:02-05' is neither k=v nor k@v

### ISSUE THREAD

**Issue by steve-chavez** [jpmens/jo#84]
Just tried to generate a date with timezone and I got this:

```bash
jo time=$(date +'%F %T-05') body=xxx

Argument `20:03:02-05' is neither k=v nor k@v
{"time":"2019-02-15","body":"xxx"}
```

No idea why it truncates the output of the `date` command. Bug maybe?

The json should be like:
```json
{"time":"2019-02-15 20:06:57-05", "body":"xxx"}
```

**Comment by gromgit** [comment]
Your command line:
```
jo time=$(date +'%F %T-05') body=xxx
```
literally expands to:
```
jo time=2019-02-15 20:06:57-05 body=xxx
```
You need to double-quote your command substitution to protect it from your shell's normal word splitting:
```
jo time="$(date +'%F %T-05')" body=xxx
```

**Comment by steve-chavez** [comment]
@gromgit Thank you.
