### ISSUE TITLE
Update homebrew for 1.2

### ISSUE THREAD

**Issue by rooftopsparrow** [jpmens/jo#85]
I was hoping you could update the homebrew formula for the newest release? If there is anything I can do to help, let me know 👍 

❤️ Thanks for the great tool!

**Comment by jpmens** [comment]
I don't think I know who actually [contributed it](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jo.rb), at least I have no recollection of doing it. Maybe you can find out via the history at that link.

**Comment by equal-l2** [comment]
I posted a PR for updating jo to 1.2. https://github.com/Homebrew/homebrew-core/pull/37589 
Once it is merged, you'll be able to get the new version via Homebrew.

**Comment by equal-l2** [comment]
@rooftopsparrow You should be able to get the new version via Homebrew now.
If you aren't, let me know.

**Comment by jpmens** [comment]
```
$ brew upgrade jo
==> Upgrading 1 outdated package:
jo 1.1 -> 1.2
==> Upgrading jo
==> Downloading https://homebrew.bintray.com/bottles/jo-1.2.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring jo-1.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/jo/1.2: 9 files, 44.2KB
Removing: /usr/local/Cellar/jo/1.1... (9 files, 42.6KB)
```

Thank you very much, @equal-l2; much appreciated!
