### ISSUE TITLE
How do I omit null/empty values?

### ISSUE THREAD

**Issue by rocketspacer** [jpmens/jo#92]
How do I omit null/empty values?

```sh
unset VALUE
jo -o key=$VALUE
```

Wanted result
```json
{
}
```

Actual result
```json
{
    "key": null
}
```

**Comment by gromgit** [comment]
> `jo -o key=$VALUE`

I assume that by `-o`, you actually meant `-p` (i.e. pretty-print).

In any event, note that the `jo` manual gives the canonical example for creating an empty object as follows:
```
$ jo < /dev/null
{}
```
So all you need to do is to ensure that you redirect `/dev/null` to stdin, and give `jo` exactly zero arguments. How to do that is somewhat shell-specific; in bash:
```
$ value=test
$ jo -p ${value:+key=}$value < /dev/null
{
   "key": "test"
}
$ unset value
$ jo -p ${value:+key=}$value < /dev/null
{}
```
The magic bash incantion `${var:+subst}` simply means "if `var` is empty or unset, replace with nothing, else replace with `subst`". Hence, `${value:+key=}$value` expands to `key=${value}` if `value` is set, or nothing at all if `value` is unset.

Also note that `jo` prefers command-line arguments to stdin, so it's always safe to redirect `/dev/null` to stdin if you'll only ever feed `jo` via the command line.
